#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
exec python -c "
import pydevd_pycharm
pydevd_pycharm.settrace('host.docker.internal', port=5678, stdout_to_server=True, stderr_to_server=True, suspend=False)
import runpy, sys
sys.argv = ['manage.py', 'runserver', '0.0.0.0:8000', '--noreload']
runpy.run_path('manage.py', run_name='__main__')
"
