# Generated by Django 6.0.6 on 2026-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_libraryasset_mime'),
        ('channels', '0005_channel_max_publishes_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryasset',
            name='license_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='libraryasset',
            name='license_type',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('OWNED', 'Owned / original'), ('LICENSED', 'Licensed (paid)'), ('CREATIVE_COMMONS', 'Creative Commons'), ('ROYALTY_FREE_VERIFIED', 'Royalty-free (verified)')], default='UNSPECIFIED', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='libraryasset',
            constraint=models.CheckConstraint(condition=models.Q(('license_type__in', ['UNSPECIFIED', 'OWNED', 'LICENSED', 'CREATIVE_COMMONS', 'ROYALTY_FREE_VERIFIED'])), name='assets_libraryasset_license_type_valid'),
        ),
    ]
