# Generated by Django 6.0.6 on 2026-07-26 07:04
#
# Widens assets_asset_kind_valid to allow FOOTAGE — backward-compatible because
# existing rows keep their current kind values; only new FOOTAGE rows are added.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_backfill_license_type'),
        ('pipelines', '0010_runcast_importance_draft_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootageCredit',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_idx', models.PositiveIntegerField()),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('license', models.CharField(max_length=64)),
                ('license_url', models.URLField(blank=True, default='')),
                (
                    'author',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                ('source_url', models.URLField()),
                (
                    'title',
                    models.CharField(blank=True, default='', max_length=300),
                ),
                ('attribution_required', models.BooleanField(default=False)),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credits',
                        to='assets.asset',
                    ),
                ),
                (
                    'run',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='footage_credits',
                        to='pipelines.pipelinerun',
                    ),
                ),
            ],
            options={
                'ordering': ['scene_idx'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='asset',
            name='assets_asset_kind_valid',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'kind__in',
                        [
                            'IMAGE',
                            'VIDEO_SEGMENT',
                            'AUDIO_VO',
                            'SUBTITLE',
                            'FINAL_VIDEO',
                            'THUMBNAIL',
                            'TRANSCRIPT',
                            'DOC',
                            'FOOTAGE',
                        ],
                    ),
                ),
                name='assets_asset_kind_valid',
            ),
        ),
    ]
