# Generated by Django 6.0.6 on 2026-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_footagecredit_remove_asset_assets_asset_kind_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO_SEGMENT', 'Video Segment'), ('AUDIO_VO', 'Audio VO'), ('SUBTITLE', 'Subtitle'), ('FINAL_VIDEO', 'Final Video'), ('THUMBNAIL', 'Thumbnail'), ('TRANSCRIPT', 'Transcript'), ('DOC', 'Document'), ('FOOTAGE', 'Footage')], max_length=20),
        ),
    ]
