# Generated by Django 6.0.6 on 2026-07-30 14:36
#
# Widens assets_libraryasset_kind_valid to allow VIDEO — backward-compatible
# because existing rows keep their current kind values.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0008_alter_asset_kind_choices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libraryasset',
            name='assets_libraryasset_kind_valid',
        ),
        migrations.AlterField(
            model_name='libraryasset',
            name='kind',
            field=models.CharField(
                choices=[
                    ('WATERMARK', 'Watermark'),
                    ('INTRO', 'Intro'),
                    ('OUTRO', 'Outro'),
                    ('OVERLAY', 'Overlay'),
                    ('TRANSITION', 'Transition'),
                    ('MUSIC', 'Music'),
                    ('SFX', 'SFX'),
                    ('FONT', 'Font'),
                    ('BACKGROUND', 'Background'),
                    ('VIDEO', 'Video'),
                    ('CHARACTER_REF', 'Character Ref'),
                    ('CAPTION_STYLE', 'Caption Style'),
                    ('LUT', 'LUT'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='libraryasset',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'kind__in',
                        [
                            'WATERMARK',
                            'INTRO',
                            'OUTRO',
                            'OVERLAY',
                            'TRANSITION',
                            'MUSIC',
                            'SFX',
                            'FONT',
                            'BACKGROUND',
                            'VIDEO',
                            'CHARACTER_REF',
                            'CAPTION_STYLE',
                            'LUT',
                        ],
                    ),
                ),
                name='assets_libraryasset_kind_valid',
            ),
        ),
    ]
