# Generated by Django 5.2.11 on 2026-02-17 19:22

import django.contrib.***REMOVED***.fields
import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('youtube_video_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('youtube_video_url', models.URLField(blank=True)),
                ('youtube_upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('privacy_status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=10)),
                ('published_title', models.CharField(max_length=100)),
                ('published_description', models.TextField()),
                ('published_tags', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, help_text='If not null, video is scheduled for future publish', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('playlist_ids', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='YouTube playlist IDs this video was added to', size=None)),
                ('shorts_uploaded', models.BooleanField(default=False)),
                ('shorts_youtube_id', models.CharField(blank=True, max_length=50)),
                ('shorts_youtube_url', models.URLField(blank=True)),
                ('shorts_upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tiktok_post_id', models.CharField(blank=True, max_length=100)),
                ('tiktok_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('instagram_post_id', models.CharField(blank=True, max_length=100)),
                ('instagram_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('twitter_post_id', models.CharField(blank=True, max_length=100)),
                ('twitter_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('cards_set', models.BooleanField(default=False, help_text='Whether YouTube cards have been added')),
                ('pinned_comment_text', models.TextField(blank=True)),
                ('pinned_comment_id', models.CharField(blank=True, max_length=100)),
                ('chapters_added', models.BooleanField(default=False)),
                ('views_24h', models.PositiveIntegerField(default=0)),
                ('views_7d', models.PositiveIntegerField(default=0)),
                ('views_30d', models.PositiveIntegerField(default=0)),
                ('ctr_percent', models.FloatField(default=0.0, help_text='Click-through rate from impressions')),
                ('avg_view_duration_seconds', models.FloatField(default=0.0)),
                ('avg_view_percentage', models.FloatField(default=0.0, help_text='Average percentage of video watched')),
                ('revenue_est_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_jobs', to='channels.channel')),
                ('production_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_job', to='production.productionjob')),
            ],
            options={
                'verbose_name': 'Distribution Job',
                'verbose_name_plural': 'Distribution Jobs',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('snapshot_days_after', models.PositiveIntegerField(help_text='Days since publish when this snapshot was taken (1, 7, 30)')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('subscribers_gained', models.IntegerField(default=0)),
                ('watch_time_hrs', models.FloatField(default=0.0, help_text='Total watch time in hours')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr_percent', models.FloatField(default=0.0)),
                ('avg_view_duration_seconds', models.FloatField(default=0.0)),
                ('avg_view_percentage', models.FloatField(default=0.0)),
                ('traffic_source_data', models.JSONField(default=dict, help_text='{"suggested": 45.2, "search": 23.1, "browse": 15.5, ...}')),
                ('revenue_est_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rpm_usd', models.DecimalField(decimal_places=2, default=0, help_text='Revenue per 1000 views', max_digits=6)),
                ('performance_class', models.CharField(choices=[('VIRAL', 'Viral (>100k in 7d)'), ('ABOVE_AVG', 'Above Average'), ('AVERAGE', 'Average'), ('UNDERPERFORM', 'Underperforming')], default='UNDERPERFORM', help_text='Performance classification based on views and engagement', max_length=20)),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI analysis for feedback loop: {"what_worked": [], "what_to_improve": [], "title_assessment": "...", "recommendations": []}')),
                ('channel', models.ForeignKey(help_text='Channel for aggregated analytics', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='channels.channel')),
                ('distribution_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='distribution.distributionjob')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='distributionjob',
            index=models.Index(fields=['status', 'published_at'], name='distributio_status_611595_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionjob',
            index=models.Index(fields=['channel', 'published_at'], name='distributio_channel_4b56f8_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionjob',
            index=models.Index(fields=['youtube_video_id'], name='distributio_youtube_ff543f_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionjob',
            index=models.Index(fields=['production_job'], name='distributio_product_99f8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['distribution_job', 'snapshot_days_after'], name='distributio_distrib_ccb155_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['channel', 'created_at'], name='distributio_channel_7d8d91_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['created_at'], name='distributio_created_6f8daf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('distribution_job', 'snapshot_days_after')},
        ),
    ]
