# Generated by Django 5.2.11 on 2026-02-21 18:58

import reelforge.core.fields
import reelforge.distribution.schemas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticssnapshot",
            name="ai_insights",
            field=reelforge.core.fields.PydanticField(
                blank=True,
                default=reelforge.distribution.schemas.AIInsights,
                help_text="AI-generated performance analysis for the research feedback loop.",
                schema=reelforge.distribution.schemas.AIInsights,
            ),
        ),
        migrations.AlterField(
            model_name="analyticssnapshot",
            name="traffic_source_data",
            field=reelforge.core.fields.PydanticField(
                default=reelforge.distribution.schemas.TrafficSourceData,
                help_text="YouTube Analytics traffic source breakdown: source_name → percentage.",
                schema=reelforge.distribution.schemas.TrafficSourceData,
            ),
        ),
    ]
