# Generated by Django 5.2.11 on 2026-02-22 10:32

import reelforge.core.validators
import reelforge.distribution.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_revert_pydantic_field_to_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='ai_insights',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated performance analysis for the research feedback loop.', validators=[reelforge.core.validators.PydanticValidator(reelforge.distribution.schemas.AIInsights)]),
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='traffic_source_data',
            field=models.JSONField(default=dict, help_text='YouTube Analytics traffic source breakdown: source_name → percentage.', validators=[reelforge.core.validators.PydanticValidator(reelforge.distribution.schemas.TrafficSourceData)]),
        ),
    ]
