# Generated by Django 5.2.11 on 2026-03-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_analyticssnapshot_ai_insights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionjob',
            name='instagram_post_id',
        ),
        migrations.RemoveField(
            model_name='distributionjob',
            name='instagram_status',
        ),
        migrations.RemoveField(
            model_name='distributionjob',
            name='tiktok_post_id',
        ),
        migrations.RemoveField(
            model_name='distributionjob',
            name='tiktok_status',
        ),
        migrations.RemoveField(
            model_name='distributionjob',
            name='twitter_post_id',
        ),
        migrations.RemoveField(
            model_name='distributionjob',
            name='twitter_status',
        ),
    ]
