volumes:
  ***REMOVED***_local_***REMOVED***_data: {}
  ***REMOVED***_local_***REMOVED***_data_backups: {}
  ***REMOVED***_local_redis_data: {}

x-app: &app
  image: tricelex/***REMOVED***:local
  volumes:
    - /app/.venv
    - .:/app:z
  env_file:
    - ./.envs/.local/.django
    - ./.envs/.local/.***REMOVED***

services:
  django:
    <<: *app
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: ***REMOVED***_local_django
    depends_on:
      - ***REMOVED***
      - redis
#      - mailpit
    ports:
      - '8000:8000'
    command: /start

  ***REMOVED***:
    build:
      context: .
      dockerfile: ./compose/production/***REMOVED***/Dockerfile
    container_name: ***REMOVED***_local_***REMOVED***
    volumes:
      - ***REMOVED***_local_***REMOVED***_data:/var/lib/***REMOVED***ql/18/docker
      - ***REMOVED***_local_***REMOVED***_data_backups:/backups
    env_file:
      - ./.envs/.local/.***REMOVED***
    ports:
      - "5435:5432"

#  mailpit:
#    image: docker.io/axllent/mailpit:latest
#    container_name: ***REMOVED***_local_mailpit
#    ports:
#      - "8025:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: ***REMOVED***_local_redis
    volumes:
      - ***REMOVED***_local_redis_data:/data

  celeryworker:
    <<: *app
    container_name: ***REMOVED***_local_celeryworker
    depends_on:
      - redis
      - ***REMOVED***
#      - mailpit
    ports:
      - "5679:5679"
    command: /start-celeryworker-debug

#  celerybeat:
#    <<: *app
#    container_name: ***REMOVED***_local_celerybeat
#    depends_on:
#      - redis
#      - ***REMOVED***
#      - mailpit
#    ports: []
#    command: /start-celerybeat

  flower:
    <<: *app
    container_name: ***REMOVED***_local_flower
    depends_on:
      - redis
      - ***REMOVED***
    ports:
      - '5555:5555'
    command: /start-flower
