---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

services:
  db:
    image: "postgres:18-alpine"
    restart: unless-stopped
    volumes:
      # Postgres 18 default PGDATA is `/var/lib/postgresql/18/docker`,
      # so we mount the parent directory to persist the actual data path.
      - postgres-data:/var/lib/postgresql
    networks:
      - backend-net
    env_file: ./config/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - backend-net
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    networks:
      - backend-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s

  web:
    <<: &web
      # Image name is changed in production:
      image: "reelforge:dev"
      build:
        target: development_build
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - "reelforge:dev"
          - "reelforge:latest"

      volumes:
        - django-static:/var/www/django/static
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
      networks:
        - backend-net
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db

    command: python -We -bb manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: /bin/sh /code/docker/django/healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  worker:
    <<: *web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: python -m taskiq worker server.common.broker:broker server.apps.main.tasks
    healthcheck:
      disable: true

networks:
  backend-net:

volumes:
  postgres-data:
  django-static:
  redis-data:
  rabbitmq-data:
