volumes:
  reelforge_local_postgres_data: {}
  reelforge_local_postgres_data_backups: {}
  reelforge_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: reelforge_local_django
    container_name: reelforge_local_django
    depends_on:
      - postgres
      - redis
#      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: reelforge_production_postgres
    container_name: reelforge_local_postgres
    volumes:
      - reelforge_local_postgres_data:/var/lib/postgresql/18/docker
      - reelforge_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5435:5432"

#  mailpit:
#    image: docker.io/axllent/mailpit:latest
#    container_name: reelforge_local_mailpit
#    ports:
#      - "8025:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: reelforge_local_redis
    volumes:
      - reelforge_local_redis_data:/data

  celeryworker:
    <<: *django
    image: reelforge_local_celeryworker
    container_name: reelforge_local_celeryworker
    depends_on:
      - redis
      - postgres
#      - mailpit
    ports:
      - "5679:5679"
    command: /start-celeryworker-debug

#  celerybeat:
#    <<: *django
#    image: reelforge_local_celerybeat
#    container_name: reelforge_local_celerybeat
#    depends_on:
#      - redis
#      - postgres
#      - mailpit
#    ports: []
#    command: /start-celerybeat

  flower:
    <<: *django
    image: reelforge_local_flower
    container_name: reelforge_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
