[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/django/Dockerfile"
dockerBuildContext = "."

[deploy]
startCommand = "python /code/manage.py runserver 0.0.0.0:8000"
healthcheckPath = "/health/?format=json"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
