[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/django/Dockerfile"
dockerBuildContext = "."

[deploy]
startCommand = "python /code/manage.py migrate --noinput && exec gunicorn --config /code/docker/django/gunicorn_config.py server.wsgi"
healthcheckPath = "/health/?format=json"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
