# Generated by Django 6.0.6 on 2026-06-13 19:08

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('LONGFORM', 'Long-form'),
                            ('SHORTS', 'Shorts'),
                            ('CLIPPING', 'Clipping'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'publish_mode',
                    models.CharField(
                        choices=[('auto', 'Auto'), ('review', 'Review')],
                        default='review',
                        max_length=10,
                    ),
                ),
                (
                    'gates',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    'character_design_mode',
                    models.CharField(
                        choices=[
                            ('interactive', 'Interactive'),
                            ('auto', 'Auto'),
                            ('none', 'None'),
                        ],
                        default='interactive',
                        max_length=15,
                    ),
                ),
                (
                    'default_budget_usd',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ('voice_id', models.CharField(blank=True, max_length=100)),
                ('stability', models.FloatField(default=0.5)),
                ('similarity_boost', models.FloatField(default=0.75)),
                ('wpm', models.PositiveIntegerField(default=158)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q((
                            'kind__in',
                            ['LONGFORM', 'SHORTS', 'CLIPPING'],
                        )),
                        name='channels_channel_kind_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            'publish_mode__in',
                            ['auto', 'review'],
                        )),
                        name='channels_channel_publish_mode_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            'character_design_mode__in',
                            ['interactive', 'auto', 'none'],
                        )),
                        name='channels_channel_character_design_mode_valid',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='ChannelBranding',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'watermark_position',
                    models.CharField(default='bottom_right', max_length=20),
                ),
                ('watermark_opacity', models.FloatField(default=0.6)),
                (
                    'music_pool_tags',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                    ),
                ),
                ('thumbnail_palette', models.JSONField(default=dict)),
                (
                    'caption_style',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'channel',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='branding',
                        to='channels.channel',
                    ),
                ),
                (
                    'fonts',
                    models.ManyToManyField(
                        blank=True,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'intro',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'outro',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'watermark',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('APPROVED', 'Approved'),
                            ('RETIRED', 'Retired'),
                        ],
                        default='DRAFT',
                        max_length=10,
                    ),
                ),
                ('appearance_prompt', models.TextField()),
                ('persona', models.TextField(blank=True)),
                (
                    'total_creation_cost_usd',
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                    ),
                ),
                (
                    'origin',
                    models.CharField(
                        choices=[('LIBRARY', 'Library'), ('RUN', 'Run')],
                        default='RUN',
                        max_length=10,
                    ),
                ),
                (
                    'channel',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='characters',
                        to='channels.channel',
                    ),
                ),
                (
                    'hero_ref',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CharacterGenerationSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rounds', models.JSONField(default=list)),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to='channels.character',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterSheetItem',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('label', models.CharField(max_length=60)),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sheet',
                        to='channels.character',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NicheConfig',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.TextField(blank=True)),
                ('angle', models.TextField(blank=True)),
                (
                    'banned_topics',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                    ),
                ),
                ('lore_document', models.TextField(blank=True)),
                (
                    'channel',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='niche_config',
                        to='channels.channel',
                    ),
                ),
                (
                    'format',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='prompts.storyformat',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Niche config',
            },
        ),
        migrations.CreateModel(
            name='YouTubeCredential',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                (
                    'channel',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='youtube_credential',
                        to='channels.channel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'status__in',
                    ['DRAFT', 'APPROVED', 'RETIRED'],
                )),
                name='channels_character_status_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(
                condition=models.Q(('origin__in', ['LIBRARY', 'RUN'])),
                name='channels_character_origin_valid',
            ),
        ),
    ]
