# Generated by Django 6.0.6 on 2026-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_default_blueprint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='max_publishes_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
