# Generated by Django 6.0.6 on 2026-07-07 19:39

import uuid

import django.contrib.***REMOVED***.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channel_max_publishes_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyStyleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_movements', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list)),
                ('transition_styles', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list)),
                ('sfx_pool_tags', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list)),
                ('min_cuts_per_minute', models.PositiveSmallIntegerField(default=4)),
                ('max_cuts_per_minute', models.PositiveSmallIntegerField(default=8)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_style', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
