# Generated by Django 6.0.6 on 2026-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_assemblystyleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblystyleconfig',
            name='music_bed_gain_db',
            field=models.FloatField(default=-18.0, help_text='Background music gain in dB relative to dialogue.'),
        ),
    ]
