# Generated by Django 6.0.6 on 2026-07-26 07:09

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('channels', '0007_assemblystyleconfig_music_bed_gain_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootageSourcingConfig',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'enabled_providers',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        help_text='Ordered provider priority. Order is significant.',
                    ),
                ),
                (
                    'sourcing_mode',
                    models.CharField(
                        choices=[
                            ('stock_first', 'Stock first'),
                            ('archival_first', 'Archival first'),
                            ('balanced', 'Balanced'),
                        ],
                        default='stock_first',
                        max_length=15,
                    ),
                ),
                ('ai_fallback_enabled', models.BooleanField(default=True)),
                (
                    'rerank_mode',
                    models.CharField(
                        choices=[
                            ('vision', 'Vision model'),
                            ('metadata', 'Metadata only'),
                            ('none', 'No re-ranking'),
                        ],
                        default='vision',
                        max_length=10,
                    ),
                ),
                (
                    'candidates_per_scene',
                    models.PositiveSmallIntegerField(default=8),
                ),
                ('min_clip_width', models.PositiveIntegerField(default=1280)),
                ('min_clip_duration_s', models.FloatField(default=3.0)),
                (
                    'allowed_licenses',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                    ),
                ),
                ('require_attribution', models.BooleanField(default=True)),
                (
                    'channel',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='footage_sourcing',
                        to='channels.channel',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Footage sourcing config',
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q((
                            'sourcing_mode__in',
                            ['stock_first', 'archival_first', 'balanced'],
                        )),
                        name='channels_footagesourcing_mode_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            'rerank_mode__in',
                            ['vision', 'metadata', 'none'],
                        )),
                        name='channels_footagesourcing_rerank_valid',
                    ),
                ],
            },
        ),
    ]
