# Generated by Django 6.0.6 on 2026-09-02 11:17

import django.contrib.***REMOVED***.fields
from django.db import migrations, models

import server.apps.channels.models


class Migration(migrations.Migration):
    dependencies = [
        ('channels', '0011_nicheconfig_visual_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footagesourcingconfig',
            name='enabled_providers',
            field=django.contrib.***REMOVED***.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=server.apps.channels.models.default_enabled_providers,
                help_text='Ordered provider priority. Order is significant.',
            ),
        ),
    ]
