# Generated by Django 6.0.6 on 2026-09-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('channels', '0012_alter_footagesourcingconfig_enabled_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='footagesourcingconfig',
            name='max_ai_fallback_per_run',
            field=models.PositiveSmallIntegerField(db_default=15, default=15),
        ),
    ]
