# Generated by Django 6.0.6 on 2026-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('channels', '0013_add_max_ai_fallback_per_run'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='footagesourcingconfig',
            name='channels_footagesourcing_mode_valid',
        ),
        migrations.AlterField(
            model_name='footagesourcingconfig',
            name='sourcing_mode',
            field=models.CharField(
                choices=[
                    ('stock_first', 'Stock first'),
                    ('archival_first', 'Archival first'),
                    ('balanced', 'Balanced'),
                    ('ai_only', 'AI only'),
                ],
                default='stock_first',
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name='footagesourcingconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'sourcing_mode__in',
                    ['stock_first', 'archival_first', 'balanced', 'ai_only'],
                )),
                name='channels_footagesourcing_mode_valid',
            ),
        ),
    ]
