# Generated by Django 6.0.6 on 2026-06-15 16:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('channels', '0002_character_source_run'),
        (
            'pipelines',
            '0002_pipelineblueprint_pipelines_pipelineblueprint_kind_valid_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'youtube_video_id',
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('UPLOADING', 'Uploading'),
                            ('COMPLETED', 'Completed'),
                            ('FAILED', 'Failed'),
                        ],
                        default='PENDING',
                        max_length=10,
                    ),
                ),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_snapshot', models.JSONField(default=dict)),
                ('error', models.JSONField(blank=True, null=True)),
                (
                    'channel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='publish_jobs',
                        to='channels.channel',
                    ),
                ),
                (
                    'run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='publish_jobs',
                        to='pipelines.pipelinerun',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q((
                            'status__in',
                            ['PENDING', 'UPLOADING', 'COMPLETED', 'FAILED'],
                        )),
                        name='publishing_publishjob_status_valid',
                    ),
                ],
            },
        ),
    ]
