# Generated by Django 6.0.6 on 2026-07-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishjob',
            name='tested_candidate_ranks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publishjob',
            name='thumbnail_asset_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publishjob',
            name='thumbnail_tested',
            field=models.BooleanField(default=False),
        ),
    ]
