# Generated by Django 5.2.11 on 2026-02-17 19:22

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('voiceover_provider', models.CharField(blank=True, help_text='TTS provider used (elevenlabs, openai_tts, etc.)', max_length=50)),
                ('voiceover_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('voiceover_file', models.FileField(blank=True, help_text='Final merged voiceover MP3', null=True, upload_to='audio/full/')),
                ('voiceover_duration_seconds', models.FloatField(default=0.0)),
                ('voiceover_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('images_provider', models.CharField(blank=True, help_text='Image provider used (fal_ai, replicate, dalle, etc.)', max_length=50)),
                ('images_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('images_generated_count', models.PositiveSmallIntegerField(default=0)),
                ('images_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='audio/music/')),
                ('music_url', models.URLField(blank=True, help_text='URL to royalty-free music track')),
                ('music_title', models.CharField(blank=True, max_length=255)),
                ('music_style', models.CharField(blank=True, help_text='Music genre/style (cinematic, upbeat, calm, etc.)', max_length=50)),
                ('music_volume_pct', models.FloatField(default=0.08, help_text='Music volume as percentage of voiceover (0.08 = 8%)')),
                ('music_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('thumbnails_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('thumbnails_generated_count', models.PositiveSmallIntegerField(default=0)),
                ('selected_thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/selected/')),
                ('thumbnails_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('visual_timeline', models.JSONField(blank=True, default=list, help_text='Master timeline coordinating all assets: [{"start_ms": 0, "end_ms": 15000, "image_file_id": "...", "segment_text": "...", "section": "intro", "animation_type": "KEN_BURNS"}, ...]')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_jobs', to='channels.channel')),
                ('script_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_job', to='scripts.scriptjob')),
            ],
            options={
                'verbose_name': 'Asset Job',
                'verbose_name_plural': 'Asset Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('position_index', models.PositiveSmallIntegerField(help_text='Order in video timeline')),
                ('prompt', models.TextField(help_text='Image generation prompt')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_selected', models.BooleanField(default=True, help_text='Whether to use this image in final video')),
                ('section', models.CharField(blank=True, help_text='Script section this image belongs to', max_length=50)),
                ('timestamp_approx', models.CharField(blank=True, help_text="Approximate timestamp (e.g., '1:23', '0:45')", max_length=20)),
                ('animation_type', models.CharField(choices=[('NONE', 'No Animation'), ('KEN_BURNS', 'Ken Burns (Zoom + Pan)'), ('ZOOM', 'Zoom Only'), ('PAN', 'Pan Only'), ('FADE', 'Fade In/Out')], default='KEN_BURNS', max_length=20)),
                ('duration_seconds', models.FloatField(default=5.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('image_provider', models.CharField(blank=True, max_length=50)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.assetjob')),
            ],
            options={
                'verbose_name': 'Generated Image',
                'verbose_name_plural': 'Generated Images',
                'ordering': ['position_index'],
            },
        ),
        migrations.CreateModel(
            name='ThumbnailOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('option_number', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='thumbnails/options/')),
                ('is_selected', models.BooleanField(default=False)),
                ('ctr_score', models.FloatField(default=0.0, help_text='AI-predicted CTR potential (0-10)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('image_provider', models.CharField(blank=True, max_length=50)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_options', to='assets.assetjob')),
            ],
            options={
                'verbose_name': 'Thumbnail Option',
                'verbose_name_plural': 'Thumbnail Options',
                'ordering': ['option_number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceoverSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('segment_index', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, help_text='Script section (intro, body, outro, etc.)', max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/segments/')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('start_ms', models.PositiveIntegerField(default=0, help_text='Start position in merged full audio (milliseconds)')),
                ('end_ms', models.PositiveIntegerField(default=0, help_text='End position in merged full audio (milliseconds)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tts_provider', models.CharField(blank=True, max_length=50)),
                ('tts_voice_id', models.CharField(blank=True, max_length=100)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceover_segments', to='assets.assetjob')),
            ],
            options={
                'verbose_name': 'Voiceover Segment',
                'verbose_name_plural': 'Voiceover Segments',
                'ordering': ['segment_index'],
            },
        ),
        migrations.AddIndex(
            model_name='assetjob',
            index=models.Index(fields=['status', 'created_at'], name='assets_asse_status_2c0caf_idx'),
        ),
        migrations.AddIndex(
            model_name='assetjob',
            index=models.Index(fields=['channel', 'created_at'], name='assets_asse_channel_f3d52a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetjob',
            index=models.Index(fields=['script_job'], name='assets_asse_script__875832_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['asset_job', 'position_index'], name='assets_gene_asset_j_2ef763_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbnailoption',
            index=models.Index(fields=['asset_job', 'is_selected'], name='assets_thum_asset_j_0e6faf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnailoption',
            unique_together={('asset_job', 'option_number')},
        ),
        migrations.AddIndex(
            model_name='voiceoversegment',
            index=models.Index(fields=['asset_job', 'segment_index'], name='assets_voic_asset_j_08feb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voiceoversegment',
            unique_together={('asset_job', 'segment_index')},
        ),
    ]
