# Generated by Django 5.2.11 on 2026-02-18 08:47

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('voiceover_provider', models.CharField(blank=True, help_text='TTS provider used (e.g., elevenlabs, openai_tts)', max_length=50, verbose_name='Voiceover Provider')),
                ('voiceover_full_file', models.FileField(blank=True, help_text='Merged full voiceover audio file', null=True, upload_to='assets/audio/full/%Y/%m/%d/', verbose_name='Full Voiceover File')),
                ('voiceover_duration_sec', models.FloatField(default=0.0, help_text='Total duration of all voiceover segments combined', verbose_name='Voiceover Duration (seconds)')),
                ('voiceover_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Voiceover Status')),
                ('voiceover_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Total cost for voiceover generation', max_digits=8, verbose_name='Voiceover Cost (USD)')),
                ('music_file', models.FileField(blank=True, help_text='Selected background music track', null=True, upload_to='assets/music/%Y/%m/%d/', verbose_name='Background Music File')),
                ('music_style', models.CharField(blank=True, help_text='Style of background music (e.g., inspiring_cinematic, calm_ambient)', max_length=100, verbose_name='Music Style')),
                ('music_volume_pct', models.FloatField(default=0.08, help_text='Background music volume as percentage of voiceover volume', verbose_name='Music Volume (%)')),
                ('music_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Music Status')),
                ('images_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Images Status')),
                ('images_provider', models.CharField(blank=True, help_text='Image generation provider used (e.g., fal_ai, replicate)', max_length=50, verbose_name='Image Provider')),
                ('images_count', models.PositiveSmallIntegerField(default=0, help_text='Number of background images generated', verbose_name='Images Count')),
                ('images_cost_usd', models.DecimalField(decimal_places=4, default=0, help_text='Total cost for image generation', max_digits=8, verbose_name='Images Cost (USD)')),
                ('thumbnails_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Thumbnails Status')),
                ('selected_thumbnail', models.FileField(blank=True, help_text='The thumbnail selected for the video', null=True, upload_to='assets/thumbnails/selected/%Y/%m/%d/', verbose_name='Selected Thumbnail')),
                ('visual_timeline', models.JSONField(blank=True, default=list, help_text='Timeline of images synchronized with voiceover segments: [{start_ms, end_ms, image_file_id, segment_text, section, animation_type}]', verbose_name='Visual Timeline')),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, help_text='Total cost for all asset generation (voiceover + images + thumbnails)', max_digits=10, verbose_name='Total Cost (USD)')),
                ('script_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_job', to='scripts.scriptjob', verbose_name='Script Job')),
            ],
            options={
                'verbose_name': 'Asset Job',
                'verbose_name_plural': 'Asset Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('position_idx', models.PositiveSmallIntegerField(help_text='Order of this image in the video timeline', verbose_name='Position Index')),
                ('prompt_used', models.TextField(help_text='Image generation prompt used', verbose_name='Prompt Used')),
                ('image_file', models.FileField(blank=True, help_text='Generated background image', null=True, upload_to='assets/images/%Y/%m/%d/', verbose_name='Image File')),
                ('provider', models.CharField(blank=True, help_text='Image generation provider used', max_length=50, verbose_name='Provider')),
                ('is_selected', models.BooleanField(default=True, help_text='Whether this image option was selected for the video', verbose_name='Selected')),
                ('section', models.CharField(blank=True, help_text='Script section this image is associated with', max_length=50, verbose_name='Script Section')),
                ('timestamp_approx', models.CharField(blank=True, help_text="Approximate timestamp in video (e.g., '0:45', '2:30')", max_length=20, verbose_name='Approximate Timestamp')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this image', max_digits=8, verbose_name='Generation Cost (USD)')),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.assetjob', verbose_name='Asset Job')),
            ],
            options={
                'verbose_name': 'Generated Image',
                'verbose_name_plural': 'Generated Images',
                'ordering': ['asset_job', 'position_idx'],
            },
        ),
        migrations.CreateModel(
            name='ThumbnailOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('option_number', models.PositiveSmallIntegerField(help_text='Thumbnail option number (0, 1, 2)', verbose_name='Option Number')),
                ('image_file', models.FileField(help_text='Generated thumbnail image', upload_to='assets/thumbnails/options/%Y/%m/%d/', verbose_name='Thumbnail Image')),
                ('prompt_used', models.TextField(blank=True, help_text='Thumbnail generation prompt used', verbose_name='Prompt Used')),
                ('provider', models.CharField(blank=True, help_text='Image generation provider used', max_length=50, verbose_name='Provider')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether this thumbnail was selected for the video', verbose_name='Selected')),
                ('ctr_score', models.FloatField(default=0.0, help_text='AI-predicted click-through rate potential (0-10)', verbose_name='CTR Score')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this thumbnail', max_digits=8, verbose_name='Generation Cost (USD)')),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='assets.assetjob', verbose_name='Asset Job')),
            ],
            options={
                'verbose_name': 'Thumbnail Option',
                'verbose_name_plural': 'Thumbnail Options',
                'ordering': ['asset_job', 'option_number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceoverSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('segment_id', models.PositiveSmallIntegerField(help_text='Order of this segment in the full script', verbose_name='Segment ID')),
                ('text', models.TextField(help_text='Text that was converted to speech for this segment', verbose_name='Script Text')),
                ('section', models.CharField(blank=True, help_text='Script section (e.g., HOOK, INTRO_BRIDGE, SECTION_1, OUTRO_CTA)', max_length=50, verbose_name='Script Section')),
                ('audio_file', models.FileField(blank=True, help_text='Generated audio file for this segment', null=True, upload_to='assets/audio/segments/%Y/%m/%d/', verbose_name='Audio File')),
                ('duration_sec', models.FloatField(default=0.0, help_text='Duration of this audio segment', verbose_name='Duration (seconds)')),
                ('start_ms', models.PositiveIntegerField(default=0, help_text='Start position in full merged voiceover (milliseconds)', verbose_name='Start Time (ms)')),
                ('end_ms', models.PositiveIntegerField(default=0, help_text='End position in full merged voiceover (milliseconds)', verbose_name='End Time (ms)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('tts_provider_used', models.CharField(blank=True, help_text='TTS provider used to generate this segment', max_length=50, verbose_name='TTS Provider')),
                ('voice_id_used', models.CharField(blank=True, help_text='Voice ID used for this segment', max_length=255, verbose_name='Voice ID')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this segment', max_digits=8, verbose_name='Generation Cost (USD)')),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceover_segments', to='assets.assetjob', verbose_name='Asset Job')),
            ],
            options={
                'verbose_name': 'Voiceover Segment',
                'verbose_name_plural': 'Voiceover Segments',
                'ordering': ['asset_job', 'segment_id'],
            },
        ),
        migrations.AddIndex(
            model_name='assetjob',
            index=models.Index(fields=['status', 'created_at'], name='assets_asse_status_2c0caf_idx'),
        ),
        migrations.AddIndex(
            model_name='assetjob',
            index=models.Index(fields=['script_job'], name='assets_asse_script__875832_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['asset_job', 'position_idx'], name='assets_gene_asset_j_35166f_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['is_selected'], name='assets_gene_is_sele_ff4263_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbnailoption',
            index=models.Index(fields=['asset_job', 'is_selected'], name='assets_thum_asset_j_0e6faf_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbnailoption',
            index=models.Index(fields=['-ctr_score'], name='assets_thum_ctr_sco_c847b4_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceoversegment',
            index=models.Index(fields=['asset_job', 'segment_id'], name='assets_voic_asset_j_ab1b35_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceoversegment',
            index=models.Index(fields=['status'], name='assets_voic_status_4725df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voiceoversegment',
            unique_together={('asset_job', 'segment_id')},
        ),
    ]
