# Generated by Django 5.2.11 on 2026-02-21 18:58

import ***REMOVED***.assets.schemas
import ***REMOVED***.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetjob",
            name="visual_timeline",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.assets.schemas.VisualTimeline,
                help_text="Composited timeline driving VideoRenderer — maps time windows to images.",
                schema=***REMOVED***.assets.schemas.VisualTimeline,
                verbose_name="Visual Timeline",
            ),
        ),
    ]
