# Generated by Django 5.2.11 on 2026-02-22 10:32

import ***REMOVED***.assets.schemas
import ***REMOVED***.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_revert_pydantic_field_to_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetjob',
            name='visual_timeline',
            field=models.JSONField(blank=True, default=list, help_text='Composited timeline driving VideoRenderer — maps time windows to images.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.assets.schemas.VisualTimeline)], verbose_name='Visual Timeline'),
        ),
    ]
