# Generated by Django 5.2.11 on 2026-03-03 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assetjob_visual_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('run_number', models.PositiveSmallIntegerField(help_text='Sequential attempt number (1, 2, 3…)', verbose_name='Run Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('images_count', models.PositiveSmallIntegerField(default=0, verbose_name='Images Count')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Total Cost (USD)')),
                ('generation_config', models.JSONField(blank=True, default=dict, help_text='Prompts, size, style params used for this run', verbose_name='Generation Config')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery Task ID')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_runs', to='assets.assetjob', verbose_name='Asset Job')),
            ],
            options={
                'verbose_name': 'Image Generation Run',
                'verbose_name_plural': 'Image Generation Runs',
                'ordering': ['asset_job', 'run_number'],
            },
        ),
        migrations.AddField(
            model_name='assetjob',
            name='selected_image_run',
            field=models.ForeignKey(blank=True, help_text='The image generation run whose images feed downstream rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.imagegenerationrun', verbose_name='Selected Image Run'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image_run',
            field=models.ForeignKey(blank=True, help_text='The specific image generation run this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.imagegenerationrun', verbose_name='Image Generation Run'),
        ),
        migrations.CreateModel(
            name='ThumbnailRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('run_number', models.PositiveSmallIntegerField(help_text='Sequential attempt number (1, 2, 3…)', verbose_name='Run Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('options_count', models.PositiveSmallIntegerField(default=0, verbose_name='Options Count')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Total Cost (USD)')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery Task ID')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_runs', to='assets.assetjob', verbose_name='Asset Job')),
            ],
            options={
                'verbose_name': 'Thumbnail Run',
                'verbose_name_plural': 'Thumbnail Runs',
                'ordering': ['asset_job', 'run_number'],
            },
        ),
        migrations.AddField(
            model_name='assetjob',
            name='selected_thumbnail_run',
            field=models.ForeignKey(blank=True, help_text='The thumbnail run whose options feed the distribution step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.thumbnailrun', verbose_name='Selected Thumbnail Run'),
        ),
        migrations.AddField(
            model_name='thumbnailoption',
            name='thumbnail_run',
            field=models.ForeignKey(blank=True, help_text='The specific thumbnail run this option belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assets.thumbnailrun', verbose_name='Thumbnail Run'),
        ),
        migrations.CreateModel(
            name='VideoClipGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('run_number', models.PositiveSmallIntegerField(help_text='Sequential attempt number (1, 2, 3…)', verbose_name='Run Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('clips_count', models.PositiveSmallIntegerField(default=0, verbose_name='Clips Count')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Total Cost (USD)')),
                ('generation_config', models.JSONField(blank=True, default=dict, help_text='Prompts, duration, provider params used for this run', verbose_name='Generation Config')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery Task ID')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clip_runs', to='assets.assetjob', verbose_name='Asset Job')),
                ('image_run', models.ForeignKey(blank=True, help_text="Which image run's images were animated", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_clip_runs', to='assets.imagegenerationrun', verbose_name='Source Image Run')),
            ],
            options={
                'verbose_name': 'Video Clip Generation Run',
                'verbose_name_plural': 'Video Clip Generation Runs',
                'ordering': ['asset_job', 'run_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedVideoClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('position_idx', models.PositiveSmallIntegerField(help_text='Order of this clip in the video timeline', verbose_name='Position Index')),
                ('prompt_used', models.TextField(help_text='Animation prompt used to generate this clip', verbose_name='Prompt Used')),
                ('clip_file', models.FileField(blank=True, help_text='Generated video clip file (MP4)', null=True, upload_to='assets/clips/%Y/%m/%d/', verbose_name='Clip File')),
                ('duration_sec', models.FloatField(default=0.0, verbose_name='Duration (seconds)')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('is_selected', models.BooleanField(default=True, help_text='Whether this clip is selected for rendering', verbose_name='Selected')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Generation Cost (USD)')),
                ('source_image', models.ForeignKey(blank=True, help_text='The still image that was animated into this clip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_clips', to='assets.generatedimage', verbose_name='Source Image')),
                ('video_clip_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='assets.videoclipgenerationrun', verbose_name='Video Clip Run')),
            ],
            options={
                'verbose_name': 'Generated Video Clip',
                'verbose_name_plural': 'Generated Video Clips',
                'ordering': ['video_clip_run', 'position_idx'],
            },
        ),
        migrations.AddField(
            model_name='assetjob',
            name='selected_video_clip_run',
            field=models.ForeignKey(blank=True, help_text='The video clip run whose clips feed downstream rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.videoclipgenerationrun', verbose_name='Selected Video Clip Run'),
        ),
        migrations.CreateModel(
            name='VoiceoverRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('run_number', models.PositiveSmallIntegerField(help_text='Sequential attempt number (1, 2, 3…)', verbose_name='Run Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('provider', models.CharField(blank=True, help_text='TTS provider used (e.g., elevenlabs, openai_tts)', max_length=50, verbose_name='Provider')),
                ('voice_id', models.CharField(blank=True, max_length=255, verbose_name='Voice ID')),
                ('merged_audio_file', models.FileField(blank=True, help_text='Combined voiceover audio for this run', null=True, upload_to='assets/audio/full/%Y/%m/%d/', verbose_name='Merged Audio File')),
                ('total_duration_sec', models.FloatField(default=0.0, verbose_name='Total Duration (seconds)')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Total Cost (USD)')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery Task ID')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceover_runs', to='assets.assetjob', verbose_name='Asset Job')),
            ],
            options={
                'verbose_name': 'Voiceover Run',
                'verbose_name_plural': 'Voiceover Runs',
                'ordering': ['asset_job', 'run_number'],
            },
        ),
        migrations.AddField(
            model_name='assetjob',
            name='selected_voiceover_run',
            field=models.ForeignKey(blank=True, help_text='The voiceover run whose merged audio feeds downstream rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.voiceoverrun', verbose_name='Selected Voiceover Run'),
        ),
        migrations.AddField(
            model_name='voiceoversegment',
            name='voiceover_run',
            field=models.ForeignKey(blank=True, help_text='The specific voiceover run this segment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='assets.voiceoverrun', verbose_name='Voiceover Run'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrun',
            index=models.Index(fields=['asset_job', 'run_number'], name='assets_imag_asset_j_0afc17_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrun',
            index=models.Index(fields=['status'], name='assets_imag_status_1e7cbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagegenerationrun',
            unique_together={('asset_job', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='thumbnailrun',
            index=models.Index(fields=['asset_job', 'run_number'], name='assets_thum_asset_j_430d67_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbnailrun',
            index=models.Index(fields=['status'], name='assets_thum_status_d72d24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnailrun',
            unique_together={('asset_job', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='videoclipgenerationrun',
            index=models.Index(fields=['asset_job', 'run_number'], name='assets_vide_asset_j_73e293_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclipgenerationrun',
            index=models.Index(fields=['status'], name='assets_vide_status_b530dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoclipgenerationrun',
            unique_together={('asset_job', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='generatedvideoclip',
            index=models.Index(fields=['video_clip_run', 'position_idx'], name='assets_gene_video_c_6fde4f_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideoclip',
            index=models.Index(fields=['is_selected'], name='assets_gene_is_sele_a74fae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedvideoclip',
            unique_together={('video_clip_run', 'position_idx')},
        ),
        migrations.AddIndex(
            model_name='voiceoverrun',
            index=models.Index(fields=['asset_job', 'run_number'], name='assets_voic_asset_j_eca90c_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceoverrun',
            index=models.Index(fields=['status'], name='assets_voic_status_3b823f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voiceoverrun',
            unique_together={('asset_job', 'run_number')},
        ),
    ]
