# Generated by Django 5.2.11 on 2026-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_run_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='generation_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this image', max_digits=10, verbose_name='Generation Cost (USD)'),
        ),
        migrations.AlterField(
            model_name='thumbnailoption',
            name='generation_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this thumbnail', max_digits=10, verbose_name='Generation Cost (USD)'),
        ),
        migrations.AlterField(
            model_name='voiceoversegment',
            name='generation_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this segment', max_digits=10, verbose_name='Generation Cost (USD)'),
        ),
    ]
