# Generated by Django 5.2.11 on 2026-02-17 19:22

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('channels', '0001_initial'),
        ('distribution', '0001_initial'),
        ('production', '0001_initial'),
        ('research', '0001_initial'),
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('overall_status', django_fsm.FSMField(choices=[('INITIALIZING', 'Initializing'), ('RESEARCHING', 'Researching Topics'), ('SCRIPTING', 'Writing Script'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('GENERATING_ASSETS', 'Generating Assets'), ('RENDERING', 'Rendering Video'), ('QA', 'Quality Assurance'), ('UPLOADING', 'Uploading to YouTube'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='INITIALIZING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the pipeline actually started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the pipeline finished (PUBLISHED state)', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the pipeline failed (FAILED state)', null=True)),
                ('orchestrator_run_id', models.CharField(blank=True, help_text='OpenAI Agents SDK run ID', max_length=255)),
                ('orchestrator_turns', models.PositiveIntegerField(default=0, help_text='Number of agent turns in this run')),
                ('current_stage', models.CharField(blank=True, help_text='Current stage name for display/logging purposes', max_length=50)),
                ('last_agent_decision', models.JSONField(blank=True, default=dict, help_text='Last decision made by OrchestratorAgent')),
                ('total_agent_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Sum of all AI agent costs (LLM calls)', max_digits=10)),
                ('total_asset_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Sum of all asset generation costs (TTS, images, thumbnails)', max_digits=10)),
                ('final_video_title', models.CharField(blank=True, max_length=255)),
                ('final_video_url', models.URLField(blank=True)),
                ('final_video_duration_seconds', models.FloatField(default=0.0)),
                ('asset_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='assets.assetjob')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='channels.channel')),
                ('distribution_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='distribution.distributionjob')),
                ('production_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='production.productionjob')),
                ('research_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='research.researchjob')),
                ('script_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='scripts.scriptjob')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='research.topicidea')),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('RETRY', 'Retry Attempt'), ('MANUAL', 'Manual Intervention')], db_index=True, default='INFO', max_length=20)),
                ('event_name', models.CharField(help_text="e.g., 'FSM transition', 'Agent decision', 'Operator approval'", max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Structured event data')),
                ('triggered_by_agent', models.CharField(blank=True, help_text='Agent name if event was from agent run', max_length=100)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_events', to=settings.AUTH_USER_MODEL)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pipeline.pipelinerun')),
            ],
            options={
                'verbose_name': 'Pipeline Event',
                'verbose_name_plural': 'Pipeline Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['overall_status', 'created_at'], name='pipeline_pi_overall_a78d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['channel', 'created_at'], name='pipeline_pi_channel_196077_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['orchestrator_run_id'], name='pipeline_pi_orchest_8a880f_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineevent',
            index=models.Index(fields=['pipeline_run', 'created_at'], name='pipeline_pi_pipelin_f3bcd9_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineevent',
            index=models.Index(fields=['event_type', 'created_at'], name='pipeline_pi_event_t_dd79eb_idx'),
        ),
    ]
