# Generated by Django 5.2.11 on 2026-02-21 18:58

import reelforge.core.fields
import reelforge.pipeline.schemas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineevent",
            name="metadata",
            field=reelforge.core.fields.PydanticField(
                default=reelforge.pipeline.schemas.EventMetadata,
                help_text="Structured event data",
                schema=reelforge.pipeline.schemas.EventMetadata,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="last_agent_decision",
            field=reelforge.core.fields.PydanticField(
                blank=True,
                default=reelforge.pipeline.schemas.AgentDecision,
                help_text="Last decision made by OrchestratorAgent",
                schema=reelforge.pipeline.schemas.AgentDecision,
            ),
        ),
    ]
