# Generated by Django 5.2.11 on 2026-02-22 10:32

import reelforge.core.validators
import reelforge.pipeline.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_revert_pydantic_field_to_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineevent',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Structured event data', validators=[reelforge.core.validators.PydanticValidator(reelforge.pipeline.schemas.EventMetadata)]),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='last_agent_decision',
            field=models.JSONField(blank=True, default=dict, help_text='Last decision made by OrchestratorAgent', validators=[reelforge.core.validators.PydanticValidator(reelforge.pipeline.schemas.AgentDecision)]),
        ),
    ]
