# Generated by Django 5.2.11 on 2026-03-03 16:47

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_fix_statelog_object_id_for_uuid'),
        ('production', '0005_add_scene_breakdown_audio_mix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='audio_mix_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.audiomixjob'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='scene_breakdown_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.scenebreakdownjob'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='overall_status',
            field=django_fsm.FSMField(choices=[('INITIALIZING', 'Initializing'), ('RESEARCHING', 'Researching Topics'), ('SCRIPTING', 'Writing Script'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('SCENE_BREAKDOWN', 'Breaking Down Scenes'), ('GENERATING_ASSETS', 'Generating Assets'), ('AUDIO_MIX', 'Mixing Audio'), ('CLIP_GENERATION', 'Generating Video Clips'), ('RENDERING', 'Rendering Video'), ('QA', 'Quality Assurance'), ('UPLOADING', 'Uploading to YouTube'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='INITIALIZING', max_length=50, protected=True),
        ),
    ]
