# Generated by Django 5.2.11 on 2026-02-17 19:22

import django.contrib.***REMOVED***.fields
import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('research_data', models.JSONField(blank=True, default=dict, help_text='Facts, stats, sources gathered during script research')),
                ('research_sources', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.URLField(), default=list, help_text='URLs of sources used in script', size=None)),
                ('generated_hooks', models.JSONField(blank=True, default=list, help_text='[{"text": "...", "type": "question|statement|story", "score": 8.5}, ...]')),
                ('selected_hook_idx', models.PositiveSmallIntegerField(default=0, help_text='Index of selected hook in generated_hooks array')),
                ('hook_score', models.FloatField(default=0.0, help_text='0-10 hook quality score from agent')),
                ('script_text', models.TextField(blank=True)),
                ('script_version', models.PositiveSmallIntegerField(default=1, help_text='Current version number (increments on major changes)')),
                ('script_file', models.FileField(blank=True, help_text='Exported script file for download/archive', null=True, upload_to='scripts/')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('estimated_duration_mins', models.FloatField(default=0.0, help_text='Estimated video duration based on word count')),
                ('main_points', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.TextField(), default=list, help_text='Key points covered in script', size=None)),
                ('readability_score', models.FloatField(default=0.0, help_text='0-10 readability score (Flesch-Kincaid equivalent)')),
                ('qa_issues_found', models.JSONField(blank=True, default=list, help_text='[{"issue": "long sentence", "location": "para 3", "severity": "low"}, ...]')),
                ('qa_issues_fixed', models.JSONField(blank=True, default=list, help_text='Issues that have been resolved')),
                ('final_title', models.CharField(blank=True, max_length=200)),
                ('final_description', models.TextField(blank=True, help_text='YouTube video description')),
                ('seo_tags', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('category', models.CharField(blank=True, help_text="YouTube category (e.g., 'Education', 'Howto & Style')", max_length=100)),
                ('chapters', models.JSONField(default=list, help_text='[{"timestamp": "0:00", "title": "Introduction"}, ...]')),
                ('pinned_comment', models.TextField(blank=True, help_text='Comment to pin on video')),
                ('broll_suggestions', models.JSONField(blank=True, default=list, help_text='[{"timestamp_approx": 15, "description": "Show chart of rising prices"}, ...]')),
                ('segments', models.JSONField(blank=True, default=list, help_text='[{"segment_id": 1, "text": "...", "section": "intro", "approx_start_sec": 0, "approx_end_sec": 15}, ...]')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approved', models.BooleanField(default=False, help_text='True if approved automatically after delay')),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scripts', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_jobs', to='channels.channel')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script_job', to='research.topicidea')),
            ],
            options={
                'verbose_name': 'Script Job',
                'verbose_name_plural': 'Script Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('version_number', models.PositiveSmallIntegerField(default=1)),
                ('script_text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('change_summary', models.TextField(blank=True, help_text='What changed in this revision')),
                ('agent_feedback', models.TextField(blank=True, help_text='Agent evaluation of this revision')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_revisions', to=settings.AUTH_USER_MODEL)),
                ('script_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scripts.scriptjob')),
            ],
            options={
                'verbose_name': 'Script Revision',
                'verbose_name_plural': 'Script Revisions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='scriptjob',
            index=models.Index(fields=['status', 'approved'], name='scripts_scr_status_b02a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptjob',
            index=models.Index(fields=['channel', 'created_at'], name='scripts_scr_channel_9a5ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptjob',
            index=models.Index(fields=['topic'], name='scripts_scr_topic_i_f28079_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptrevision',
            index=models.Index(fields=['script_job', 'version_number'], name='scripts_scr_script__e8d610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptrevision',
            unique_together={('script_job', 'version_number')},
        ),
    ]
