# Generated by Django 5.2.11 on 2026-02-21 18:58

import ***REMOVED***.core.fields
import ***REMOVED***.scripts.schemas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptjob",
            name="broll_suggestions",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.scripts.schemas.BRollSuggestions,
                help_text="B-roll cues consumed by AssetJob for image generation.",
                schema=***REMOVED***.scripts.schemas.BRollSuggestions,
            ),
        ),
        migrations.AlterField(
            model_name="scriptjob",
            name="chapters",
            field=***REMOVED***.core.fields.PydanticField(
                default=***REMOVED***.scripts.schemas.ChapterList,
                help_text="YouTube chapter markers for the video.",
                schema=***REMOVED***.scripts.schemas.ChapterList,
            ),
        ),
        migrations.AlterField(
            model_name="scriptjob",
            name="generated_hooks",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.scripts.schemas.GeneratedHooks,
                help_text="Agent-generated hook variations for the video opening.",
                schema=***REMOVED***.scripts.schemas.GeneratedHooks,
            ),
        ),
        migrations.AlterField(
            model_name="scriptjob",
            name="qa_issues_fixed",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.scripts.schemas.QAIssueList,
                help_text="QA issues that have been resolved.",
                schema=***REMOVED***.scripts.schemas.QAIssueList,
            ),
        ),
        migrations.AlterField(
            model_name="scriptjob",
            name="qa_issues_found",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.scripts.schemas.QAIssueList,
                help_text="QA issues found in the script.",
                schema=***REMOVED***.scripts.schemas.QAIssueList,
            ),
        ),
        migrations.AlterField(
            model_name="scriptjob",
            name="research_data",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.scripts.schemas.ResearchData,
                help_text="Facts, stats, sources gathered during script research",
                schema=***REMOVED***.scripts.schemas.ResearchData,
            ),
        ),
        migrations.AlterField(
            model_name="scriptjob",
            name="segments",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.scripts.schemas.SegmentList,
                help_text="Pre-chunked TTS segments driving VoiceoverSegment creation.",
                schema=***REMOVED***.scripts.schemas.SegmentList,
            ),
        ),
    ]
