# Generated by Django 5.2.11 on 2026-02-22 10:32

import ***REMOVED***.core.validators
import ***REMOVED***.scripts.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_revert_pydantic_field_to_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptjob',
            name='broll_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='B-roll cues consumed by AssetJob for image generation.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.BRollSuggestions)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='chapters',
            field=models.JSONField(default=list, help_text='YouTube chapter markers for the video.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.ChapterList)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='generated_hooks',
            field=models.JSONField(blank=True, default=list, help_text='Agent-generated hook variations for the video opening.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.GeneratedHooks)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='qa_issues_fixed',
            field=models.JSONField(blank=True, default=list, help_text='QA issues that have been resolved.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.QAIssueList)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='qa_issues_found',
            field=models.JSONField(blank=True, default=list, help_text='QA issues found in the script.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.QAIssueList)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='research_data',
            field=models.JSONField(blank=True, default=dict, help_text='Facts, stats, sources gathered during script research', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.ResearchData)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='segments',
            field=models.JSONField(blank=True, default=list, help_text='Pre-chunked TTS segments driving VoiceoverSegment creation.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.scripts.schemas.SegmentList)]),
        ),
    ]
