# Generated by Django 5.2.11 on 2026-02-27 09:36

import django.contrib.postgres.fields
import reelforge.core.validators
import reelforge.scripts.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_alter_scriptjob_broll_suggestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptjob',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text='YouTube chapter markers for the video.', validators=[reelforge.core.validators.PydanticValidator(reelforge.scripts.schemas.ChapterList)]),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='main_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Key points covered in script', size=None),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='research_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='URLs of sources used in script', size=None),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='seo_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
