# Generated by Django 5.2.11 on 2026-02-27 11:42

import django.contrib.postgres.fields
import reelforge.core.validators
import reelforge.scripts.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_add_blank_true_to_arrayfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptjob',
            name='quality_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Agent quality self-assessment (hook_score, faceless_compliance, etc.).', validators=[reelforge.core.validators.PydanticValidator(reelforge.scripts.schemas.ScriptQualityFlagsSchema)]),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='ready_for_production',
            field=models.BooleanField(default=False, help_text='True when agent self-review passes all quality checks.'),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Agent explanation if ready_for_production is False.'),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='search_hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='3-5 hashtags for video description footer.', size=None),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Parsed script sections with per-section narration and b-roll indices.', validators=[reelforge.core.validators.PydanticValidator(reelforge.scripts.schemas.ScriptSectionList)]),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='thumbnail_emotion',
            field=models.CharField(blank=True, help_text='Single emotion word for thumbnail style (e.g. shock, curiosity).', max_length=50),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='thumbnail_text',
            field=models.CharField(blank=True, help_text='2-5 word overlay text for thumbnail generation agent.', max_length=200),
        ),
        # Convert research_sources from character varying[] to jsonb.
        # PostgreSQL cannot cast varchar[] directly to jsonb, so we use to_jsonb() USING clause.
        migrations.RunSQL(
            sql="""
                ALTER TABLE "scripts_scriptjob"
                ALTER COLUMN "research_sources" TYPE jsonb
                USING to_jsonb("research_sources");
            """,
            reverse_sql="""
                ALTER TABLE "scripts_scriptjob"
                ALTER COLUMN "research_sources" TYPE character varying[]
                USING ARRAY(SELECT jsonb_array_elements_text("research_sources"));
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='scriptjob',
                    name='research_sources',
                    field=models.JSONField(blank=True, default=list, help_text='Sources used in script with URL, title, and key claim.', validators=[reelforge.core.validators.PydanticValidator(reelforge.scripts.schemas.ResearchSourceList)]),
                ),
            ],
        ),
    ]
