# Generated by Django 5.2.11 on 2026-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_scriptjob_enrich_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptjob',
            name='change_request',
            field=models.TextField(blank=True, default='', help_text='Operator change request for the next script revision. Cleared after the revision task runs.'),
        ),
    ]
