# Generated by Django 5.2.11 on 2026-03-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_scriptjob_add_change_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptjob',
            name='readability_score',
        ),
        migrations.RemoveField(
            model_name='scriptjob',
            name='script_file',
        ),
        migrations.RemoveField(
            model_name='scriptjob',
            name='script_version',
        ),
    ]
