# Generated by Django 5.2.11 on 2026-03-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0008_remove_script_version_script_file_readability_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptjob",
            name="narrative_mode",
            field=models.CharField(
                blank=True,
                help_text="Narrative mode selected by ScriptAgent (REVEAL, CHRONICLE, TRANSFORMATION, etc.)",
                max_length=30,
                verbose_name="Narrative Mode",
            ),
        ),
    ]
