# Generated by Django 5.2.11 on 2026-03-23 17:47

import django.contrib.***REMOVED***.fields
import django.db.models.deletion
import django_fsm
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0009_remove_channel_youtube_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClippingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("YOUTUBE_URL", "YouTube URL"),
                            ("DIRECT_URL", "Direct URL"),
                            ("UPLOAD", "File Upload"),
                        ],
                        default="YOUTUBE_URL",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "source_video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="clipping/source/"
                    ),
                ),
                (
                    "downloaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="clipping/downloaded/"
                    ),
                ),
                ("source_title", models.CharField(blank=True, max_length=500)),
                (
                    "source_duration_sec",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("transcript_text", models.TextField(blank=True)),
                ("transcript_json", models.JSONField(default=dict)),
                ("transcription_provider", models.CharField(blank=True, max_length=50)),
                (
                    "transcription_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("clips_requested", models.PositiveIntegerField(default=5)),
                ("analysis_provider", models.CharField(blank=True, max_length=50)),
                (
                    "analysis_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("agent_run_id", models.CharField(blank=True, max_length=255)),
                (
                    "agent_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("INITIALIZING", "Initializing"),
                            ("DOWNLOADING", "Downloading"),
                            ("TRANSCRIBING", "Transcribing"),
                            ("ANALYZING", "Analyzing"),
                            ("AWAITING_CLIP_APPROVAL", "Awaiting Clip Approval"),
                            ("RENDERING", "Rendering"),
                            ("DISTRIBUTING", "Distributing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PAUSED", "Paused"),
                        ],
                        default="INITIALIZING",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clipping_jobs",
                        to="channels.channel",
                    ),
                ),
                (
                    "target_accounts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clipping_jobs",
                        to="channels.socialaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clipping Job",
                "verbose_name_plural": "Clipping Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClipCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("start_sec", models.FloatField()),
                ("end_sec", models.FloatField()),
                ("title", models.CharField(max_length=200)),
                ("hook_text", models.CharField(blank=True, max_length=200)),
                ("caption_template", models.TextField(blank=True)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("reason", models.TextField(blank=True)),
                ("transcript_excerpt", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RENDERING", "Rendering"),
                            ("RENDERED", "Rendered"),
                            ("DISTRIBUTING", "Distributing"),
                            ("DISTRIBUTED", "Distributed"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("approved", models.BooleanField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_clip_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clipping_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="clipping.clippingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Candidate",
                "verbose_name_plural": "Clip Candidates",
                "ordering": ["-relevance_score"],
            },
        ),
        migrations.CreateModel(
            name="ClipRender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("VERTICAL_9_16", "Vertical 9:16"),
                            ("LANDSCAPE_16_9", "Landscape 16:9"),
                            ("SQUARE_1_1", "Square 1:1"),
                        ],
                        default="VERTICAL_9_16",
                        max_length=20,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="clipping/renders/"
                    ),
                ),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("include_captions", models.BooleanField(default=True)),
                ("include_title_card", models.BooleanField(default=True)),
                ("include_branding", models.BooleanField(default=True)),
                ("render_config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("render_duration_sec", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renders",
                        to="clipping.clipcandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Render",
                "verbose_name_plural": "Clip Renders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClipPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("caption", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "hashtags",
                    django.contrib.***REMOVED***.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("POSTING", "Posting"),
                            ("POSTED", "Posted"),
                            ("SCHEDULED", "Scheduled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("platform_post_id", models.CharField(blank=True, max_length=255)),
                ("platform_url", models.URLField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("last_error", models.TextField(blank=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                (
                    "revenue_est_usd",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("last_analytics_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip_posts",
                        to="channels.socialaccount",
                    ),
                ),
                (
                    "render",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="clipping.cliprender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Post",
                "verbose_name_plural": "Clip Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clippingjob",
            index=models.Index(
                fields=["status", "created_at"], name="clipping_cl_status_19c8d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clippingjob",
            index=models.Index(
                fields=["channel"], name="clipping_cl_channel_f0f583_idx"
            ),
        ),
    ]
