# Generated by Django 5.2.11 on 2026-03-27 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clippingjob",
            name="transcript_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="cliprender",
            name="render_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ClipLayoutConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "render_mode",
                    models.CharField(
                        choices=[
                            ("SMART_CROP", "Smart Crop (speaker-aware)"),
                            ("SPATIAL_STACK", "Spatial Stack (two regions)"),
                            ("CENTER_CROP", "Center Crop (static)"),
                        ],
                        default="SMART_CROP",
                        max_length=20,
                    ),
                ),
                ("manual_crop_x", models.PositiveIntegerField(blank=True, null=True)),
                ("manual_crop_y", models.PositiveIntegerField(blank=True, null=True)),
                ("manual_crop_w", models.PositiveIntegerField(blank=True, null=True)),
                ("manual_crop_h", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "region_a_label",
                    models.CharField(blank=True, default="Region A", max_length=100),
                ),
                ("region_a_x", models.PositiveIntegerField(blank=True, null=True)),
                ("region_a_y", models.PositiveIntegerField(blank=True, null=True)),
                ("region_a_w", models.PositiveIntegerField(blank=True, null=True)),
                ("region_a_h", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "region_b_label",
                    models.CharField(blank=True, default="Region B", max_length=100),
                ),
                ("region_b_x", models.PositiveIntegerField(blank=True, null=True)),
                ("region_b_y", models.PositiveIntegerField(blank=True, null=True)),
                ("region_b_w", models.PositiveIntegerField(blank=True, null=True)),
                ("region_b_h", models.PositiveIntegerField(blank=True, null=True)),
                ("stack_ratio", models.FloatField(default=0.6)),
                ("face_detected", models.BooleanField(blank=True, null=True)),
                ("detection_confidence", models.FloatField(blank=True, null=True)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="clipping/previews/"
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_config",
                        to="clipping.clipcandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Layout Config",
                "verbose_name_plural": "Clip Layout Configs",
            },
        ),
    ]
