# Generated by Django 5.2.11 on 2026-03-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_cliplayout_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliplayoutconfig',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='clipping/previews/'),
        ),
        migrations.AlterField(
            model_name='clippingjob',
            name='downloaded_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='clipping/downloaded/'),
        ),
        migrations.AlterField(
            model_name='clippingjob',
            name='source_video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='clipping/source/'),
        ),
        migrations.AlterField(
            model_name='cliprender',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='clipping/renders/'),
        ),
    ]
