# Generated by Django 5.2.11 on 2026-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0003_increase_file_field_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliplayoutconfig',
            name='render_format',
            field=models.CharField(choices=[('VERTICAL_9_16', 'Vertical 9:16'), ('LANDSCAPE_16_9', 'Landscape 16:9'), ('SQUARE_1_1', 'Square 1:1')], default='VERTICAL_9_16', max_length=20),
        ),
    ]
