# Generated by Django 5.2.11 on 2026-03-29 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0011_channel_default_render_mode"),
        ("clipping", "0004_add_render_format_to_layout_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClipRenderTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("caption_enabled", models.BooleanField(default=True)),
                (
                    "caption_style",
                    models.CharField(
                        choices=[
                            ("WORD_BY_WORD", "Word by Word (karaoke)"),
                            ("CHUNKED", "Chunked Phrases (3-4 words)"),
                            ("LOWER_THIRD", "Lower Third (full segment)"),
                            ("EMOJI_ACCENT", "Emoji Accent (chunked + emoji)"),
                        ],
                        default="CHUNKED",
                        max_length=20,
                    ),
                ),
                (
                    "caption_font",
                    models.CharField(default="Montserrat-Bold", max_length=100),
                ),
                ("caption_size", models.PositiveIntegerField(default=52)),
                ("caption_color", models.CharField(default="#FFFFFF", max_length=9)),
                (
                    "caption_stroke_color",
                    models.CharField(default="#000000", max_length=9),
                ),
                ("caption_stroke_width", models.PositiveIntegerField(default=3)),
                (
                    "caption_bg_color",
                    models.CharField(blank=True, default="", max_length=9),
                ),
                (
                    "caption_position",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("CENTER", "Center"),
                            ("BOTTOM", "Bottom"),
                        ],
                        default="BOTTOM",
                        max_length=10,
                    ),
                ),
                (
                    "caption_animation",
                    models.CharField(
                        choices=[("POP", "Pop"), ("FADE", "Fade"), ("NONE", "None")],
                        default="POP",
                        max_length=10,
                    ),
                ),
                ("caption_language", models.CharField(default="en", max_length=10)),
                (
                    "caption_translate_to",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("emoji_keyword_map", models.JSONField(blank=True, default=dict)),
                ("hook_enabled", models.BooleanField(default=True)),
                (
                    "hook_style",
                    models.CharField(
                        choices=[
                            ("TITLE_CARD", "Title Card (black frame prepended)"),
                            ("OVERLAY_TOP", "Overlay Top (text over video)"),
                            ("OVERLAY_CENTER", "Overlay Center (text over video)"),
                        ],
                        default="OVERLAY_TOP",
                        max_length=20,
                    ),
                ),
                ("hook_duration_sec", models.FloatField(default=2.5)),
                (
                    "hook_font",
                    models.CharField(default="Montserrat-Bold", max_length=100),
                ),
                ("hook_size", models.PositiveIntegerField(default=60)),
                ("hook_color", models.CharField(default="#FFFFFF", max_length=9)),
                ("hook_bg_color", models.CharField(default="#CC000000", max_length=9)),
                (
                    "hook_animation",
                    models.CharField(
                        choices=[("POP", "Pop"), ("FADE", "Fade"), ("NONE", "None")],
                        default="FADE",
                        max_length=10,
                    ),
                ),
                (
                    "intro_transition",
                    models.CharField(
                        choices=[
                            ("NONE", "None (hard cut)"),
                            ("CROSSFADE", "Crossfade"),
                            ("FADE_BLACK", "Fade to Black"),
                            ("WIPE_LEFT", "Wipe Left"),
                            ("WIPE_RIGHT", "Wipe Right"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "outro_transition",
                    models.CharField(
                        choices=[
                            ("NONE", "None (hard cut)"),
                            ("CROSSFADE", "Crossfade"),
                            ("FADE_BLACK", "Fade to Black"),
                            ("WIPE_LEFT", "Wipe Left"),
                            ("WIPE_RIGHT", "Wipe Right"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("transition_duration_sec", models.FloatField(default=0.5)),
                ("watermark_enabled", models.BooleanField(default=False)),
                (
                    "watermark_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("TEXT", "Text")],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                (
                    "watermark_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "watermark_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="clipping/watermarks/"
                    ),
                ),
                (
                    "watermark_position",
                    models.CharField(
                        choices=[
                            ("TOP_LEFT", "Top Left"),
                            ("TOP_RIGHT", "Top Right"),
                            ("BOTTOM_LEFT", "Bottom Left"),
                            ("BOTTOM_RIGHT", "Bottom Right"),
                        ],
                        default="BOTTOM_RIGHT",
                        max_length=15,
                    ),
                ),
                ("watermark_opacity", models.FloatField(default=0.6)),
                ("watermark_size", models.PositiveIntegerField(default=32)),
                ("progress_bar_enabled", models.BooleanField(default=False)),
                (
                    "progress_bar_position",
                    models.CharField(
                        choices=[("TOP", "Top"), ("BOTTOM", "Bottom")],
                        default="TOP",
                        max_length=10,
                    ),
                ),
                (
                    "progress_bar_color",
                    models.CharField(default="#FFFFFF", max_length=9),
                ),
                ("progress_bar_height", models.PositiveIntegerField(default=6)),
                ("music_enabled", models.BooleanField(default=False)),
                ("music_volume_db", models.FloatField(default=-20.0)),
                ("music_fade_in_sec", models.FloatField(default=1.0)),
                ("music_fade_out_sec", models.FloatField(default=1.0)),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip_render_template",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Render Template",
                "verbose_name_plural": "Clip Render Templates",
            },
        ),
        migrations.CreateModel(
            name="ClipMediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("INTRO", "Intro"), ("OUTRO", "Outro")],
                        default="INTRO",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=500, upload_to="clipping/media_assets/"
                    ),
                ),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Media Asset",
                "verbose_name_plural": "Clip Media Assets",
                "ordering": ["asset_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["channel", "asset_type", "is_active"],
                        name="clipping_cl_channel_307b20_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClipMusicAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=500, upload_to="clipping/music_assets/"
                    ),
                ),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                ("bpm", models.FloatField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_assets",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Music Asset",
                "verbose_name_plural": "Clip Music Assets",
                "ordering": ["genre", "name"],
                "indexes": [
                    models.Index(
                        fields=["channel", "is_active"],
                        name="clipping_cl_channel_fb9eef_idx",
                    )
                ],
            },
        ),
    ]
