# Generated by Django 5.2.11 on 2026-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clipping", "0009_remove_redundant_stage_result_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="clipcandidate",
            name="render_gates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cliprender",
            name="paused_at_stage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliprender",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("PAUSED_AT_GATE", "Paused at Gate"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
