# Generated by Django 5.2.11 on 2026-04-06 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0011_channel_default_render_mode"),
        ("clipping", "0010_render_gates_and_pause_at_gate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clipmediaasset",
            name="clipping_cl_channel_307b20_idx",
        ),
        migrations.RemoveIndex(
            model_name="clipmusicasset",
            name="clipping_cl_channel_fb9eef_idx",
        ),
        migrations.RemoveIndex(
            model_name="clippingjob",
            name="clipping_cl_channel_f0f583_idx",
        ),
        migrations.RemoveField(
            model_name="clipmediaasset",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="clipmusicasset",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="clippingjob",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="clippingjob",
            name="target_accounts",
        ),
        migrations.RemoveField(
            model_name="cliprendertemplate",
            name="channel",
        ),
        migrations.AddField(
            model_name="clipmediaasset",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="clipping/media_assets/thumbs/",
            ),
        ),
        migrations.AddField(
            model_name="clipmusicasset",
            name="waveform_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="clipping/music_assets/waveforms/",
            ),
        ),
        migrations.AddField(
            model_name="clippingjob",
            name="analysis_manifest",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clippingjob",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clipping_jobs",
                to="channels.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="clippingjob",
            name="thumbnail_strip_file",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="clipping/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="clippingjob",
            name="waveform_data_file",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="clipping/waveforms/"
            ),
        ),
        migrations.AddField(
            model_name="cliprendertemplate",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliprendertemplate",
            name="name",
            field=models.CharField(default="Default Template", max_length=100),
        ),
        migrations.AddField(
            model_name="clipstyleconfig",
            name="render_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seeded_style_configs",
                to="clipping.cliprendertemplate",
            ),
        ),
        migrations.AlterField(
            model_name="clippingjob",
            name="source_duration_sec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="clipmediaasset",
            index=models.Index(
                fields=["asset_type", "is_active"],
                name="clipping_cl_asset_t_a6187d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clipmusicasset",
            index=models.Index(
                fields=["is_active"], name="clipping_cl_is_acti_2f9750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clippingjob",
            index=models.Index(
                fields=["social_account"], name="clipping_cl_social__572f0d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cliprendertemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_render_template",
            ),
        ),
    ]
