# Generated by Django 5.2.11 on 2026-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clipping", "0013_seed_default_render_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="clipcandidate",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clippingjob",
            name="skip_analysis",
            field=models.BooleanField(default=False),
        ),
    ]
