# Generated by Django 5.2.11 on 2026-02-18 08:47

import django.contrib.***REMOVED***.fields
import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('trigger_source', models.CharField(choices=[('SCHEDULED', 'Scheduled Auto-Research'), ('MANUAL', 'Manual Trigger'), ('AUTO', 'Auto-Triggered (Gap Analysis)')], default='SCHEDULED', max_length=20)),
                ('search_keywords', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Keywords used for this research run', size=None)),
                ('competitor_channels_analyzed', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='YouTube channel IDs analyzed', size=None)),
                ('trend_data_raw', models.JSONField(blank=True, default=dict, help_text='Raw data from Google Trends, YouTube search, etc.')),
                ('competitor_data_raw', models.JSONField(blank=True, default=dict, help_text='Raw competitor channel analysis data')),
                ('gap_analysis_raw', models.JSONField(blank=True, default=dict, help_text='Raw gap detection and opportunity scoring data')),
                ('topics_discovered', models.PositiveSmallIntegerField(default=0)),
                ('topics_approved', models.PositiveSmallIntegerField(default=0)),
                ('topics_rejected', models.PositiveSmallIntegerField(default=0)),
                ('min_search_volume', models.PositiveIntegerField(default=1000)),
                ('max_competition', models.CharField(choices=[('LOW', 'Low Competition'), ('MEDIUM', 'Medium Competition'), ('HIGH', 'High Competition')], default='MEDIUM', max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_jobs', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Research Job',
                'verbose_name_plural': 'Research Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('title_idea', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('angle', models.TextField(blank=True, help_text='Unique angle or hook for this topic')),
                ('keywords', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('estimated_search_volume', models.PositiveIntegerField(default=0)),
                ('competition_level', models.CharField(choices=[('LOW', 'Low Competition'), ('MEDIUM', 'Medium Competition'), ('HIGH', 'High Competition')], default='MEDIUM', max_length=10)),
                ('trend_direction', models.CharField(choices=[('RISING', 'Rising'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], default='STABLE', max_length=10)),
                ('trend_score', models.FloatField(default=0.0, help_text='0-10 trend score from agent')),
                ('competitor_video_count', models.PositiveSmallIntegerField(default=0)),
                ('avg_competitor_views', models.PositiveIntegerField(default=0)),
                ('gap_opportunity_score', models.FloatField(default=0.0, help_text='0-10 gap opportunity score')),
                ('thumbnail_concept', models.TextField(blank=True)),
                ('why_it_works', models.TextField(blank=True)),
                ('suggested_sources', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('reddit_questions', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_source', models.CharField(choices=[('MANUAL', 'Manual Approval'), ('AUTO', 'Auto-Approved (Delay)'), ('AGENT', 'Agent-Approved')], default='MANUAL', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_topics', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_ideas', to='channels.channel')),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='research.researchjob')),
            ],
            options={
                'verbose_name': 'Topic Idea',
                'verbose_name_plural': 'Topic Ideas',
                'ordering': ['-trend_score', '-gap_opportunity_score'],
            },
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['status', 'created_at'], name='research_re_status_4adb58_idx'),
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['channel', 'created_at'], name='research_re_channel_e08855_idx'),
        ),
        migrations.AddIndex(
            model_name='topicidea',
            index=models.Index(fields=['status', 'approved'], name='research_to_status_29c538_idx'),
        ),
        migrations.AddIndex(
            model_name='topicidea',
            index=models.Index(fields=['channel', 'created_at'], name='research_to_channel_3a8f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='topicidea',
            index=models.Index(fields=['research_job', 'approved'], name='research_to_researc_490409_idx'),
        ),
    ]
