# Generated by Django 5.2.11 on 2026-02-21 18:58

import reelforge.core.fields
import reelforge.research.schemas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchjob",
            name="competitor_data_raw",
            field=reelforge.core.fields.PydanticField(
                blank=True,
                default=reelforge.research.schemas.CompetitorDataRaw,
                help_text="Raw competitor channel analysis data",
                schema=reelforge.research.schemas.CompetitorDataRaw,
            ),
        ),
        migrations.AlterField(
            model_name="researchjob",
            name="gap_analysis_raw",
            field=reelforge.core.fields.PydanticField(
                blank=True,
                default=reelforge.research.schemas.GapAnalysisRaw,
                help_text="Raw gap detection and opportunity scoring data",
                schema=reelforge.research.schemas.GapAnalysisRaw,
            ),
        ),
        migrations.AlterField(
            model_name="researchjob",
            name="trend_data_raw",
            field=reelforge.core.fields.PydanticField(
                blank=True,
                default=reelforge.research.schemas.TrendDataRaw,
                help_text="Raw data from Google Trends, YouTube search, etc.",
                schema=reelforge.research.schemas.TrendDataRaw,
            ),
        ),
    ]
