# Generated by Django 5.2.11 on 2026-02-21 18:58

import ***REMOVED***.core.fields
import ***REMOVED***.research.schemas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchjob",
            name="competitor_data_raw",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.research.schemas.CompetitorDataRaw,
                help_text="Raw competitor channel analysis data",
                schema=***REMOVED***.research.schemas.CompetitorDataRaw,
            ),
        ),
        migrations.AlterField(
            model_name="researchjob",
            name="gap_analysis_raw",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.research.schemas.GapAnalysisRaw,
                help_text="Raw gap detection and opportunity scoring data",
                schema=***REMOVED***.research.schemas.GapAnalysisRaw,
            ),
        ),
        migrations.AlterField(
            model_name="researchjob",
            name="trend_data_raw",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.research.schemas.TrendDataRaw,
                help_text="Raw data from Google Trends, YouTube search, etc.",
                schema=***REMOVED***.research.schemas.TrendDataRaw,
            ),
        ),
    ]
