# Generated by Django 5.2.11 on 2026-02-22 10:32

import ***REMOVED***.core.validators
import ***REMOVED***.research.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_remove_competitor_channels_analyzed_add_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchjob',
            name='competitor_data_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Raw competitor channel analysis data', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.research.schemas.CompetitorDataRaw)]),
        ),
        migrations.AlterField(
            model_name='researchjob',
            name='gap_analysis_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Raw gap detection and opportunity scoring data', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.research.schemas.GapAnalysisRaw)]),
        ),
        migrations.AlterField(
            model_name='researchjob',
            name='trend_data_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Raw data from Google Trends, YouTube search, etc.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.research.schemas.TrendDataRaw)]),
        ),
    ]
