# Generated by Django 5.2.11 on 2026-02-17 19:22

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('render_engine', models.CharField(choices=[('REMOTION', 'Remotion (React)'), ('MOVIEPY', 'MoviePy (Python)'), ('FFMPEG', 'FFmpeg Direct'), ('PICTORY', 'Pictory.ai (External)')], default='MOVIEPY', max_length=20)),
                ('render_spec', models.JSONField(blank=True, default=dict, help_text='Full render specification with all settings, effects, transitions')),
                ('resolution', models.CharField(default='1920x1080', max_length=20)),
                ('fps', models.PositiveSmallIntegerField(default=30)),
                ('codec', models.CharField(default='libx264', max_length=20)),
                ('crf', models.PositiveSmallIntegerField(default=18, help_text='Constant Rate Factor (18 = high quality)')),
                ('raw_video_file', models.FileField(blank=True, help_text='Unprocessed render', null=True, upload_to='production/raw/')),
                ('processed_video_file', models.FileField(blank=True, help_text='Final video after QA fixes', null=True, upload_to='production/processed/')),
                ('shorts_video_file', models.FileField(blank=True, help_text='9:16 Shorts variant', null=True, upload_to='production/shorts/')),
                ('video_duration_sec', models.FloatField(default=0.0, help_text='Final video duration in seconds')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, help_text='Final video file size in bytes')),
                ('bitrate_kbps', models.PositiveIntegerField(default=0)),
                ('qa_passed', models.BooleanField(default=False)),
                ('qa_checks_run', models.PositiveSmallIntegerField(default=0)),
                ('qa_checks_passed', models.PositiveSmallIntegerField(default=0)),
                ('qa_results', models.JSONField(default=dict, help_text='QA check results: {audio_sync: bool, no_black_frames: bool, duration_ok: bool, ...}')),
                ('qa_notes', models.TextField(blank=True)),
                ('shorts_start_sec', models.FloatField(default=0.0, help_text='Start time of shorts clip extracted from main video')),
                ('shorts_end_sec', models.FloatField(default=0.0, help_text='End time of shorts clip extracted from main video')),
                ('shorts_selection_reason', models.TextField(blank=True, help_text='Why this segment was chosen for shorts (hook quality, engagement, etc.)')),
                ('render_duration_sec', models.FloatField(default=0.0, help_text='How long the render took in seconds')),
                ('render_worker_id', models.CharField(blank=True, max_length=255)),
                ('asset_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_job', to='assets.assetjob')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Production Job',
                'verbose_name_plural': 'Production Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='production__status_6810bd_idx'), models.Index(fields=['channel', 'created_at'], name='production__channel_024f53_idx'), models.Index(fields=['asset_job'], name='production__asset_j_cb9d15_idx')],
            },
        ),
    ]
