# Generated by Django 5.2.11 on 2026-02-21 18:58

import ***REMOVED***.core.fields
import ***REMOVED***.production.schemas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionjob",
            name="qa_results",
            field=***REMOVED***.core.fields.PydanticField(
                default=***REMOVED***.production.schemas.QAResults,
                help_text="QA check results: check_name → pass/fail.",
                schema=***REMOVED***.production.schemas.QAResults,
            ),
        ),
        migrations.AlterField(
            model_name="productionjob",
            name="render_spec",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.production.schemas.RenderSpec,
                help_text="Full render configuration consumed by VideoRenderer.",
                schema=***REMOVED***.production.schemas.RenderSpec,
            ),
        ),
    ]
