# Generated by Django 5.2.11 on 2026-03-03 16:43

import django.db.models.deletion
import django_fsm
import ***REMOVED***.core.validators
import ***REMOVED***.production.schemas
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_run_models'),
        ('production', '0004_alter_productionjob_qa_results_and_more'),
        ('scripts', '0007_scriptjob_add_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='selected_image_run',
            field=models.ForeignKey(blank=True, help_text='Image run whose images were used in rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.imagegenerationrun', verbose_name='Selected Image Run'),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='selected_video_clip_run',
            field=models.ForeignKey(blank=True, help_text='Video clip run whose clips were used in rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.videoclipgenerationrun', verbose_name='Selected Video Clip Run'),
        ),
        migrations.CreateModel(
            name='AudioMixJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('music_file', models.FileField(blank=True, help_text='Selected background music track', null=True, upload_to='assets/music/%Y/%m/%d/', verbose_name='Music File')),
                ('music_style', models.CharField(blank=True, help_text='Style of background music (e.g., inspiring_cinematic, calm_ambient)', max_length=100, verbose_name='Music Style')),
                ('music_volume_pct', models.FloatField(default=0.08, help_text='Background music volume as percentage of voiceover volume', verbose_name='Music Volume (%)')),
                ('mixed_audio_file', models.FileField(blank=True, help_text='Final mixed audio (voiceover + music)', null=True, upload_to='assets/audio/mixed/%Y/%m/%d/', verbose_name='Mixed Audio File')),
                ('mixed_duration_sec', models.FloatField(default=0.0, verbose_name='Mixed Duration (seconds)')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this mix feeds into video rendering', verbose_name='Active')),
                ('asset_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_mix_jobs', to='assets.assetjob', verbose_name='Asset Job')),
                ('voiceover_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_mix_jobs', to='assets.voiceoverrun', verbose_name='Source Voiceover Run')),
            ],
            options={
                'verbose_name': 'Audio Mix Job',
                'verbose_name_plural': 'Audio Mix Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionjob',
            name='audio_mix_job',
            field=models.ForeignKey(blank=True, help_text='Audio mix (voiceover + music) used in this production', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.audiomixjob', verbose_name='Audio Mix Job'),
        ),
        migrations.CreateModel(
            name='SceneBreakdownJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PAUSED', 'Paused (Manual Review)'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50, protected=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Operator notes')),
                ('agent_run_id', models.CharField(blank=True, max_length=255)),
                ('agent_tokens_used', models.PositiveIntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('scenes', models.JSONField(blank=True, default=list, help_text='List of scene dicts driving image/clip generation', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.production.schemas.SceneList)], verbose_name='Scenes')),
                ('total_estimated_duration', models.FloatField(default=0.0, verbose_name='Total Estimated Duration (seconds)')),
                ('scene_count', models.PositiveSmallIntegerField(default=0, verbose_name='Scene Count')),
                ('breakdown_provider', models.CharField(blank=True, help_text='LLM provider used to generate the breakdown', max_length=50, verbose_name='Breakdown Provider')),
                ('breakdown_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Breakdown Cost (USD)')),
                ('script_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scene_breakdown', to='scripts.scriptjob', verbose_name='Script Job')),
            ],
            options={
                'verbose_name': 'Scene Breakdown Job',
                'verbose_name_plural': 'Scene Breakdown Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionjob',
            name='scene_breakdown_job',
            field=models.ForeignKey(blank=True, help_text='Scene breakdown that drove asset generation for this production', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.scenebreakdownjob', verbose_name='Scene Breakdown Job'),
        ),
        migrations.AddIndex(
            model_name='audiomixjob',
            index=models.Index(fields=['asset_job', 'is_active'], name='production__asset_j_bcc5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='audiomixjob',
            index=models.Index(fields=['status', 'created_at'], name='production__status_2b159a_idx'),
        ),
        migrations.AddIndex(
            model_name='scenebreakdownjob',
            index=models.Index(fields=['status', 'created_at'], name='production__status_513e17_idx'),
        ),
        migrations.AddIndex(
            model_name='scenebreakdownjob',
            index=models.Index(fields=['script_job'], name='production__script__e66557_idx'),
        ),
    ]
