# Generated by Django 5.2.11 on 2026-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_add_scene_breakdown_audio_mix"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionjob",
            name="caption_ass_file",
            field=models.FileField(
                blank=True,
                help_text="ASS subtitle file for FFmpeg caption burning",
                null=True,
                upload_to="production/captions/ass/",
            ),
        ),
        migrations.AddField(
            model_name="productionjob",
            name="caption_srt_file",
            field=models.FileField(
                blank=True,
                help_text="SRT subtitle file generated by Whisper",
                null=True,
                upload_to="production/captions/srt/",
            ),
        ),
    ]
