# Generated by Django 5.2.11 on 2026-03-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_add_blank_to_qa_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionjob',
            name='bitrate_kbps',
        ),
        migrations.RemoveField(
            model_name='productionjob',
            name='render_worker_id',
        ),
    ]
