# Generated by Django 5.2.11 on 2026-03-23 23:21

from django.db import migrations


def clear_old_scenes(apps, schema_editor):
    SceneBreakdownJob = apps.get_model("production", "SceneBreakdownJob")
    SceneBreakdownJob.objects.update(scenes=[], scene_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_remove_render_worker_id_bitrate_kbps"),
    ]

    operations = [
        migrations.RunPython(clear_old_scenes, migrations.RunPython.noop),
    ]
