# Generated by Django 5.2.11 on 2026-02-17 19:22

import django.contrib.***REMOVED***.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived'), ('SETUP', 'Setup in Progress')], default='SETUP', max_length=20)),
                ('youtube_channel_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('youtube_handle', models.CharField(blank=True, max_length=100)),
                ('oauth_credentials', models.JSONField(blank=True, default=dict)),
                ('analytics_property', models.CharField(blank=True, max_length=100)),
                ('niche_category', models.CharField(choices=[('FINANCE', 'Personal Finance'), ('HEALTH', 'Health & Wellness'), ('PRODUCTIVITY', 'Productivity'), ('STOICISM', 'Stoicism / Philosophy'), ('TECH', 'Technology'), ('BUSINESS', 'Business'), ('TRUE_CRIME', 'True Crime'), ('HISTORY', 'History'), ('MOTIVATION', 'Motivation'), ('CUSTOM', 'Custom Niche')], max_length=30)),
                ('custom_niche', models.CharField(blank=True, max_length=100)),
                ('target_niches', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('target_audience_description', models.TextField(blank=True)),
                ('target_age_range', models.CharField(blank=True, max_length=20)),
                ('target_location', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('content_tone', models.CharField(default='conversational_authoritative', max_length=50)),
                ('video_length_min', models.PositiveSmallIntegerField(default=8)),
                ('video_length_max', models.PositiveSmallIntegerField(default=14)),
                ('upload_frequency', models.CharField(default='3x_per_week', max_length=50)),
                ('upload_schedule', models.JSONField(default=list, help_text='[{"day": "Tuesday", "time": "15:00", "timezone": "America/New_York"}, ...]')),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='channels/logos/')),
                ('brand_color_hex', models.CharField(default='#FF4500', max_length=7)),
                ('brand_color_secondary', models.CharField(default='#FFFFFF', max_length=7)),
                ('font_primary', models.CharField(default='Montserrat', max_length=50)),
                ('channel_intro_file', models.FileField(blank=True, null=True, upload_to='channels/intros/')),
                ('channel_outro_file', models.FileField(blank=True, null=True, upload_to='channels/outros/')),
                ('default_thumbnail_template', models.FileField(blank=True, null=True, upload_to='channels/thumb_templates/')),
                ('tts_provider', models.CharField(default='elevenlabs', max_length=50)),
                ('tts_voice_id', models.CharField(blank=True, max_length=100)),
                ('tts_voice_name', models.CharField(blank=True, max_length=100)),
                ('tts_stability', models.FloatField(default=0.5)),
                ('tts_similarity', models.FloatField(default=0.8)),
                ('tts_style', models.FloatField(default=0.3)),
                ('music_style', models.CharField(default='inspiring_cinematic', max_length=50)),
                ('music_volume_pct', models.FloatField(default=0.08)),
                ('default_tags', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('channel_keywords', django.contrib.***REMOVED***.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('monetization_enabled', models.BooleanField(default=False)),
                ('estimated_rpm_usd', models.DecimalField(decimal_places=2, default=3.0, max_digits=6)),
                ('llm_provider', models.CharField(blank=True, max_length=50)),
                ('image_provider', models.CharField(blank=True, max_length=50)),
                ('video_provider', models.CharField(blank=True, max_length=50)),
                ('auto_approve_scripts', models.BooleanField(default=False)),
                ('auto_approve_assets', models.BooleanField(default=False)),
                ('auto_upload', models.BooleanField(default=False)),
                ('auto_approve_delay_hrs', models.PositiveSmallIntegerField(default=12)),
                ('description_boilerplate', models.TextField(blank=True, help_text='Appended to every video description (links, disclaimer, socials)')),
                ('default_pinned_comment_template', models.TextField(blank=True)),
                ('total_videos_published', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
                ('total_subscribers', models.PositiveIntegerField(default=0)),
                ('total_revenue_est_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_analytics_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('youtube_playlist_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('niche_tag', models.CharField(blank=True, max_length=100)),
                ('auto_assign', models.BooleanField(default=True)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelCompetitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('youtube_channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_url', models.URLField()),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='channels.channel')),
            ],
            options={
                'unique_together': {('channel', 'youtube_channel_id')},
            },
        ),
    ]
