# Generated by Django 5.2.11 on 2026-02-21 18:58

import ***REMOVED***.channels.schemas
import ***REMOVED***.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="oauth_credentials",
            field=***REMOVED***.core.fields.PydanticField(
                blank=True,
                default=***REMOVED***.channels.schemas.OAuthCredentials,
                schema=***REMOVED***.channels.schemas.OAuthCredentials,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="upload_schedule",
            field=***REMOVED***.core.fields.PydanticField(
                default=***REMOVED***.channels.schemas.UploadSchedule,
                help_text="Ordered list of weekly upload time slots.",
                schema=***REMOVED***.channels.schemas.UploadSchedule,
            ),
        ),
    ]
