# Generated by Django 5.2.11 on 2026-02-21 18:58

import reelforge.channels.schemas
import reelforge.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="oauth_credentials",
            field=reelforge.core.fields.PydanticField(
                blank=True,
                default=reelforge.channels.schemas.OAuthCredentials,
                schema=reelforge.channels.schemas.OAuthCredentials,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="upload_schedule",
            field=reelforge.core.fields.PydanticField(
                default=reelforge.channels.schemas.UploadSchedule,
                help_text="Ordered list of weekly upload time slots.",
                schema=reelforge.channels.schemas.UploadSchedule,
            ),
        ),
    ]
