# Generated by Django 5.2.11 on 2026-02-22 10:32

import ***REMOVED***.channels.schemas
import ***REMOVED***.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_revert_pydantic_field_to_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='oauth_credentials',
            field=models.JSONField(blank=True, default=dict, validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.channels.schemas.OAuthCredentials)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='upload_schedule',
            field=models.JSONField(default=list, help_text='Ordered list of weekly upload time slots.', validators=[***REMOVED***.core.validators.PydanticValidator(***REMOVED***.channels.schemas.UploadSchedule)]),
        ),
    ]
