# Generated by Django 5.2.11 on 2026-03-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_oauth_credentials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelcompetitor',
            options={'ordering': ['channel', 'channel_name'], 'verbose_name': 'Channel Competitor', 'verbose_name_plural': 'Channel Competitors'},
        ),
        migrations.AlterModelOptions(
            name='channelplaylist',
            options={'ordering': ['channel', 'name'], 'verbose_name': 'Channel Playlist', 'verbose_name_plural': 'Channel Playlists'},
        ),
    ]
