# Generated by Django 5.2.11 on 2026-03-23 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0005_alter_channelcompetitor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("YOUTUBE", "YouTube"),
                            ("TIKTOK", "TikTok"),
                            ("INSTAGRAM", "Instagram"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=255)),
                ("handle", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("analytics_property", models.CharField(blank=True, max_length=255)),
                ("oauth_credentials", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_approve_clips", models.BooleanField(default=False)),
                ("clip_caption_template", models.TextField(blank=True)),
                ("max_clips_per_day", models.PositiveIntegerField(default=3)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Account",
                "verbose_name_plural": "Social Accounts",
                "ordering": ["channel", "platform"],
                "unique_together": {("channel", "platform", "account_id")},
            },
        ),
    ]
