# Generated by Django 5.2.11 on 2026-03-23 16:52

import django.contrib.***REMOVED***.fields
import ***REMOVED***.channels.schemas
import ***REMOVED***.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0006_add_socialaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_keywords",
            field=django.contrib.***REMOVED***.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="default_tags",
            field=django.contrib.***REMOVED***.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="target_location",
            field=django.contrib.***REMOVED***.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="target_niches",
            field=django.contrib.***REMOVED***.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="upload_schedule",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of weekly upload time slots.",
                validators=[
                    ***REMOVED***.core.validators.PydanticValidator(
                        ***REMOVED***.channels.schemas.UploadSchedule
                    )
                ],
            ),
        ),
    ]
