from __future__ import annotations

# Generated by Django 5.2.11 on 2026-03-23 17:05

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_youtube_credentials_forward(apps: object, schema_editor: object) -> None:
    Channel = apps.get_model("channels", "Channel")
    SocialAccount = apps.get_model("channels", "SocialAccount")

    migrated = 0
    skipped = 0
    for channel in Channel.objects.all():
        yt_id = getattr(channel, "youtube_channel_id", "") or ""
        if not yt_id:
            logger.warning(
                "Channel %s (%s) has no youtube_channel_id — skipping SocialAccount creation",
                channel.slug,
                str(channel.id),
            )
            skipped += 1
            continue

        SocialAccount.objects.get_or_create(
            channel=channel,
            platform="YOUTUBE",
            account_id=yt_id,
            defaults={
                "handle": getattr(channel, "youtube_handle", "") or "",
                "oauth_credentials": getattr(channel, "oauth_credentials", {}) or {},
                "analytics_property": getattr(channel, "analytics_property", "") or "",
                "is_active": True,
            },
        )
        migrated += 1

    logger.info("YouTube credential migration: %d migrated, %d skipped", migrated, skipped)


def migrate_youtube_credentials_backward(apps: object, schema_editor: object) -> None:
    # Reverse: delete YOUTUBE SocialAccounts (Channel fields still exist at this point)
    SocialAccount = apps.get_model("channels", "SocialAccount")
    SocialAccount.objects.filter(platform="YOUTUBE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0007_fix_channel_blank_fields"),
    ]

    operations = [
        migrations.RunPython(
            migrate_youtube_credentials_forward,
            migrate_youtube_credentials_backward,
        ),
    ]
