# Generated by Django 5.2.11 on 2026-03-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0008_migrate_youtube_credentials_to_socialaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="analytics_property",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="oauth_credentials",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="youtube_channel_id",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="youtube_handle",
        ),
    ]
