# Generated by Django 5.2.11 on 2026-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_youtube_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='should_post',
            field=models.BooleanField(default=True, help_text='When enabled, completed clip renders are automatically posted to this account.'),
        ),
    ]
