# Generated by Django 5.2.11 on 2026-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_add_should_post_to_social_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='default_layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='Default region coordinates for SPATIAL_STACK mode. Keys: region_a_label, region_a_x, region_a_y, region_a_w, region_a_h, region_b_label, region_b_x, region_b_y, region_b_w, region_b_h, stack_ratio.'),
        ),
        migrations.AddField(
            model_name='channel',
            name='default_render_mode',
            field=models.CharField(choices=[('SMART_CROP', 'Smart Crop (speaker-aware)'), ('SPATIAL_STACK', 'Spatial Stack (two regions)'), ('CENTER_CROP', 'Center Crop (static)')], default='SMART_CROP', help_text='Default render mode applied to new ClipCandidates from this channel.', max_length=20),
        ),
    ]
