# Generated by Django 6.0.6 on 2026-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NexLevChannelRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'channel_id',
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ('about', models.JSONField(blank=True, null=True)),
                (
                    'about_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('outliers', models.JSONField(blank=True, null=True)),
                (
                    'outliers_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('analytics', models.JSONField(blank=True, null=True)),
                (
                    'analytics_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('similar_channels', models.JSONField(blank=True, null=True)),
                (
                    'similar_channels_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('niche_overview', models.JSONField(blank=True, null=True)),
                (
                    'niche_overview_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('channel_analysis', models.JSONField(blank=True, null=True)),
                (
                    'channel_analysis_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('quota_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NexLev channel record',
            },
        ),
        migrations.CreateModel(
            name='NexLevSearchCacheEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cache_key',
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('quota_spent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'NexLev search cache entry',
            },
        ),
        migrations.CreateModel(
            name='NexLevVideoRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'video_id',
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ('details', models.JSONField(blank=True, null=True)),
                (
                    'details_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('transcript', models.JSONField(blank=True, null=True)),
                (
                    'transcript_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('comments', models.JSONField(blank=True, null=True)),
                (
                    'comments_fetched_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                ('quota_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NexLev video record',
            },
        ),
    ]
