# Generated by Django 6.0.6 on 2026-06-15 22:27

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assets', '0003_asset_pipeline_fks'),
        (
            'pipelines',
            '0002_pipelineblueprint_pipelines_pipelineblueprint_kind_valid_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipCandidate',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('hook_text', models.CharField(blank=True, max_length=200)),
                ('caption_template', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('transcript_excerpt', models.TextField(blank=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PROPOSED', 'Proposed'),
                            ('APPROVED', 'Approved'),
                            ('REJECTED', 'Rejected'),
                            ('RENDERING', 'Rendering'),
                            ('RENDERED', 'Rendered'),
                            ('DISTRIBUTING', 'Distributing'),
                            ('DISTRIBUTED', 'Distributed'),
                        ],
                        default='PROPOSED',
                        max_length=20,
                    ),
                ),
                ('rejection_reason', models.TextField(blank=True)),
                ('render_asset_id', models.UUIDField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                (
                    'run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clip_candidates',
                        to='pipelines.pipelinerun',
                    ),
                ),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='ClipLayoutConfig',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'render_mode',
                    models.CharField(
                        choices=[
                            ('SMART_CROP', 'Smart Crop (speaker-aware)'),
                            ('SPATIAL_STACK', 'Spatial Stack (two regions)'),
                            ('CENTER_CROP', 'Center Crop (static)'),
                        ],
                        default='SMART_CROP',
                        max_length=20,
                    ),
                ),
                (
                    'render_format',
                    models.CharField(
                        choices=[
                            ('VERTICAL_9_16', 'Vertical 9:16'),
                            ('LANDSCAPE_16_9', 'Landscape 16:9'),
                            ('SQUARE_1_1', 'Square 1:1'),
                        ],
                        default='VERTICAL_9_16',
                        max_length=20,
                    ),
                ),
                (
                    'manual_crop_x',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'manual_crop_y',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'manual_crop_w',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'manual_crop_h',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_a_x',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_a_y',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_a_w',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_a_h',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_b_x',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_b_y',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_b_w',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'region_b_h',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('stack_ratio', models.FloatField(default=0.6)),
                ('face_detected', models.BooleanField(blank=True, null=True)),
                (
                    'detection_confidence',
                    models.FloatField(blank=True, null=True),
                ),
                (
                    'candidate',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='layout_config',
                        to='clips.clipcandidate',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClipPost',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('POSTING', 'Posting'),
                            ('POSTED', 'Posted'),
                            ('FAILED', 'Failed'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                (
                    'platform_post_id',
                    models.CharField(blank=True, max_length=255),
                ),
                ('platform_url', models.URLField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                (
                    'revenue_est_usd',
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal(0),
                        max_digits=10,
                    ),
                ),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='posts',
                        to='clips.clipcandidate',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClipStyleConfig',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption_enabled', models.BooleanField(default=True)),
                (
                    'caption_style',
                    models.CharField(
                        choices=[
                            ('WORD_BY_WORD', 'Word by Word (karaoke)'),
                            ('CHUNKED', 'Chunked Phrases (3-4 words)'),
                            ('LOWER_THIRD', 'Lower Third (full segment)'),
                            ('EMOJI_ACCENT', 'Emoji Accent (chunked + emoji)'),
                        ],
                        default='CHUNKED',
                        max_length=20,
                    ),
                ),
                (
                    'caption_font',
                    models.CharField(default='Montserrat-Bold', max_length=100),
                ),
                ('caption_size', models.PositiveIntegerField(default=52)),
                (
                    'caption_color',
                    models.CharField(default='#FFFFFF', max_length=9),
                ),
                (
                    'caption_stroke_color',
                    models.CharField(default='#000000', max_length=9),
                ),
                (
                    'caption_stroke_width',
                    models.PositiveIntegerField(default=3),
                ),
                (
                    'caption_bg_color',
                    models.CharField(blank=True, default='', max_length=9),
                ),
                (
                    'caption_position',
                    models.CharField(
                        choices=[
                            ('TOP', 'Top'),
                            ('CENTER', 'Center'),
                            ('BOTTOM', 'Bottom'),
                        ],
                        default='BOTTOM',
                        max_length=10,
                    ),
                ),
                (
                    'caption_animation',
                    models.CharField(
                        choices=[
                            ('POP', 'Pop'),
                            ('FADE', 'Fade'),
                            ('NONE', 'None'),
                        ],
                        default='POP',
                        max_length=10,
                    ),
                ),
                (
                    'caption_language',
                    models.CharField(default='en', max_length=10),
                ),
                (
                    'caption_translate_to',
                    models.CharField(blank=True, default='', max_length=10),
                ),
                (
                    'emoji_keyword_map',
                    models.JSONField(blank=True, default=dict),
                ),
                ('hook_enabled', models.BooleanField(default=True)),
                (
                    'hook_style',
                    models.CharField(
                        choices=[
                            ('TITLE_CARD', 'Title Card'),
                            ('OVERLAY_TOP', 'Overlay Top'),
                            ('OVERLAY_CENTER', 'Overlay Center'),
                        ],
                        default='OVERLAY_TOP',
                        max_length=20,
                    ),
                ),
                ('hook_duration_sec', models.FloatField(default=2.5)),
                (
                    'hook_font',
                    models.CharField(default='Montserrat-Bold', max_length=100),
                ),
                ('hook_size', models.PositiveIntegerField(default=60)),
                (
                    'hook_color',
                    models.CharField(default='#FFFFFF', max_length=9),
                ),
                (
                    'hook_bg_color',
                    models.CharField(default='#CC000000', max_length=9),
                ),
                (
                    'intro_transition',
                    models.CharField(
                        choices=[
                            ('NONE', 'None (hard cut)'),
                            ('CROSSFADE', 'Crossfade'),
                            ('FADE_BLACK', 'Fade to Black'),
                        ],
                        default='NONE',
                        max_length=20,
                    ),
                ),
                (
                    'outro_transition',
                    models.CharField(
                        choices=[
                            ('NONE', 'None (hard cut)'),
                            ('CROSSFADE', 'Crossfade'),
                            ('FADE_BLACK', 'Fade to Black'),
                        ],
                        default='NONE',
                        max_length=20,
                    ),
                ),
                ('watermark_enabled', models.BooleanField(default=False)),
                (
                    'watermark_type',
                    models.CharField(
                        choices=[('IMAGE', 'Image'), ('TEXT', 'Text')],
                        default='TEXT',
                        max_length=10,
                    ),
                ),
                (
                    'watermark_text',
                    models.CharField(blank=True, default='', max_length=100),
                ),
                (
                    'watermark_position',
                    models.CharField(
                        choices=[
                            ('TOP_LEFT', 'Top Left'),
                            ('TOP_RIGHT', 'Top Right'),
                            ('BOTTOM_LEFT', 'Bottom Left'),
                            ('BOTTOM_RIGHT', 'Bottom Right'),
                        ],
                        default='BOTTOM_RIGHT',
                        max_length=15,
                    ),
                ),
                ('watermark_opacity', models.FloatField(default=0.6)),
                ('watermark_size', models.PositiveIntegerField(default=32)),
                ('progress_bar_enabled', models.BooleanField(default=False)),
                (
                    'progress_bar_position',
                    models.CharField(
                        choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom')],
                        default='TOP',
                        max_length=10,
                    ),
                ),
                (
                    'progress_bar_color',
                    models.CharField(default='#FFFFFF', max_length=9),
                ),
                ('progress_bar_height', models.PositiveIntegerField(default=6)),
                ('music_enabled', models.BooleanField(default=False)),
                ('music_volume_db', models.FloatField(default=-20.0)),
                ('music_fade_in_sec', models.FloatField(default=1.0)),
                ('music_fade_out_sec', models.FloatField(default=1.0)),
                (
                    'candidate',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='style_config',
                        to='clips.clipcandidate',
                    ),
                ),
                (
                    'intro_asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'music_asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'outro_asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
                (
                    'watermark_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClipTimedOverlay',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'overlay_type',
                    models.CharField(
                        choices=[('TEXT', 'Text'), ('IMAGE', 'Image')],
                        default='TEXT',
                        max_length=10,
                    ),
                ),
                ('text', models.CharField(blank=True, max_length=500)),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('font_size', models.PositiveIntegerField(default=40)),
                ('color', models.CharField(default='#FFFFFF', max_length=9)),
                ('opacity', models.FloatField(default=1.0)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='timed_overlays',
                        to='clips.clipcandidate',
                    ),
                ),
                (
                    'image_asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='assets.libraryasset',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='clipcandidate',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'status__in',
                    [
                        'PROPOSED',
                        'APPROVED',
                        'REJECTED',
                        'RENDERING',
                        'RENDERED',
                        'DISTRIBUTING',
                        'DISTRIBUTED',
                    ],
                )),
                name='clips_clipcandidate_status_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cliplayoutconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'render_mode__in',
                    ['SMART_CROP', 'SPATIAL_STACK', 'CENTER_CROP'],
                )),
                name='clips_clipcandidate_render_mode_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cliplayoutconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'render_format__in',
                    ['VERTICAL_9_16', 'LANDSCAPE_16_9', 'SQUARE_1_1'],
                )),
                name='clips_cliplayoutconfig_render_format_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clippost',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'status__in',
                    ['PENDING', 'POSTING', 'POSTED', 'FAILED'],
                )),
                name='clips_clippost_status_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'caption_style__in',
                    ['WORD_BY_WORD', 'CHUNKED', 'LOWER_THIRD', 'EMOJI_ACCENT'],
                )),
                name='clips_clipstyleconfig_caption_style_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'caption_position__in',
                    ['TOP', 'CENTER', 'BOTTOM'],
                )),
                name='clips_clipstyleconfig_caption_position_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'caption_animation__in',
                    ['POP', 'FADE', 'NONE'],
                )),
                name='clips_clipstyleconfig_caption_animation_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'hook_style__in',
                    ['TITLE_CARD', 'OVERLAY_TOP', 'OVERLAY_CENTER'],
                )),
                name='clips_clipstyleconfig_hook_style_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'intro_transition__in',
                    ['NONE', 'CROSSFADE', 'FADE_BLACK'],
                )),
                name='clips_clipstyleconfig_intro_transition_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'outro_transition__in',
                    ['NONE', 'CROSSFADE', 'FADE_BLACK'],
                )),
                name='clips_clipstyleconfig_outro_transition_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q(('watermark_type__in', ['IMAGE', 'TEXT'])),
                name='clips_clipstyleconfig_watermark_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'watermark_position__in',
                    ['TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT'],
                )),
                name='clips_clipstyleconfig_watermark_position_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'progress_bar_position__in',
                    ['TOP', 'BOTTOM'],
                )),
                name='clips_clipstyleconfig_progress_bar_position_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cliptimedoverlay',
            constraint=models.CheckConstraint(
                condition=models.Q(('overlay_type__in', ['TEXT', 'IMAGE'])),
                name='clips_cliptimedoverlay_overlay_type_valid',
            ),
        ),
    ]
