# Generated by Django 6.0.6 on 2026-06-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliplayoutconfig',
            name='clips_clipcandidate_render_mode_valid',
        ),
        migrations.AddConstraint(
            model_name='cliplayoutconfig',
            constraint=models.CheckConstraint(condition=models.Q(('render_mode__in', ['SMART_CROP', 'SPATIAL_STACK', 'CENTER_CROP'])), name='clips_cliplayoutconfig_render_mode_valid'),
        ),
    ]
