# Generated by Django 6.0.6 on 2026-07-06 15:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_libraryasset_mime'),
        ('clips', '0005_clipcandidate_preview_asset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipTimedSfx',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_sec', models.FloatField()),
                ('volume_db', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='clipstyleconfig',
            name='clips_clipstyleconfig_caption_style_valid',
        ),
        migrations.RemoveConstraint(
            model_name='clipstyleconfig',
            name='clips_clipstyleconfig_intro_transition_valid',
        ),
        migrations.RemoveConstraint(
            model_name='clipstyleconfig',
            name='clips_clipstyleconfig_outro_transition_valid',
        ),
        migrations.RemoveConstraint(
            model_name='clipstyleconfig',
            name='clips_clipstyleconfig_watermark_position_valid',
        ),
        migrations.RemoveConstraint(
            model_name='cliptimedoverlay',
            name='clips_cliptimedoverlay_overlay_type_valid',
        ),
        migrations.AddField(
            model_name='cliplayoutconfig',
            name='fit_mode',
            field=models.CharField(choices=[('CROP', 'Crop'), ('BLUR_FILL', 'Blurred Background Fill')], default='CROP', max_length=10),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='brightness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='caption_font_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='caption_highlight_color',
            field=models.CharField(default='#FFD400', max_length=9),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='caption_uppercase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='color_filter',
            field=models.CharField(choices=[('NONE', 'None'), ('VIVID', 'Vivid'), ('MOODY', 'Moody'), ('WARM', 'Warm'), ('COOL', 'Cool'), ('BLACK_WHITE', 'Black & White'), ('VINTAGE', 'Vintage')], default='NONE', max_length=15),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='contrast',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='hook_animation',
            field=models.CharField(choices=[('NONE', 'None'), ('FADE', 'Fade'), ('POP', 'Pop'), ('SLIDE_LEFT', 'Slide Left'), ('SLIDE_RIGHT', 'Slide Right'), ('SLIDE_UP', 'Slide Up'), ('SLIDE_DOWN', 'Slide Down')], default='NONE', max_length=15),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='hook_font_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='intro_transition_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='intro_transition_duration_sec',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='lut_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='outro_transition_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='outro_transition_duration_sec',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='playback_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='saturation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='watermark_color',
            field=models.CharField(default='#FFFFFF', max_length=9),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='watermark_font',
            field=models.CharField(choices=[('MONTSERRAT_BOLD', 'Montserrat Bold'), ('POPPINS_BOLD', 'Poppins Bold'), ('INTER_BOLD', 'Inter Bold'), ('ROBOTO_BOLD', 'Roboto Bold'), ('OSWALD_BOLD', 'Oswald Bold'), ('BEBAS_NEUE', 'Bebas Neue'), ('ANTON', 'Anton'), ('ARCHIVO_BLACK', 'Archivo Black'), ('BANGERS', 'Bangers'), ('PERMANENT_MARKER', 'Permanent Marker'), ('CAVEAT_BOLD', 'Caveat Bold'), ('LOBSTER', 'Lobster'), ('PLAYFAIR_DISPLAY_BOLD', 'Playfair Display Bold'), ('RIGHTEOUS', 'Righteous'), ('LUCKIEST_GUY', 'Luckiest Guy'), ('PACIFICO', 'Pacifico')], default='MONTSERRAT_BOLD', max_length=30),
        ),
        migrations.AddField(
            model_name='clipstyleconfig',
            name='watermark_font_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='cliptimedoverlay',
            name='animation',
            field=models.CharField(choices=[('NONE', 'None'), ('FADE', 'Fade'), ('POP', 'Pop'), ('SLIDE_LEFT', 'Slide Left'), ('SLIDE_RIGHT', 'Slide Right'), ('SLIDE_UP', 'Slide Up'), ('SLIDE_DOWN', 'Slide Down')], default='NONE', max_length=15),
        ),
        migrations.AddField(
            model_name='cliptimedoverlay',
            name='font',
            field=models.CharField(choices=[('MONTSERRAT_BOLD', 'Montserrat Bold'), ('POPPINS_BOLD', 'Poppins Bold'), ('INTER_BOLD', 'Inter Bold'), ('ROBOTO_BOLD', 'Roboto Bold'), ('OSWALD_BOLD', 'Oswald Bold'), ('BEBAS_NEUE', 'Bebas Neue'), ('ANTON', 'Anton'), ('ARCHIVO_BLACK', 'Archivo Black'), ('BANGERS', 'Bangers'), ('PERMANENT_MARKER', 'Permanent Marker'), ('CAVEAT_BOLD', 'Caveat Bold'), ('LOBSTER', 'Lobster'), ('PLAYFAIR_DISPLAY_BOLD', 'Playfair Display Bold'), ('RIGHTEOUS', 'Righteous'), ('LUCKIEST_GUY', 'Luckiest Guy'), ('PACIFICO', 'Pacifico')], default='MONTSERRAT_BOLD', max_length=30),
        ),
        migrations.AddField(
            model_name='cliptimedoverlay',
            name='font_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='cliptimedoverlay',
            name='shape',
            field=models.CharField(choices=[('RECTANGLE', 'Rectangle'), ('CIRCLE', 'Circle'), ('ROUNDED', 'Rounded Rectangle')], default='RECTANGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='cliptimedoverlay',
            name='video_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset'),
        ),
        migrations.AddField(
            model_name='cliptimedoverlay',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clipstyleconfig',
            name='caption_font',
            field=models.CharField(choices=[('MONTSERRAT_BOLD', 'Montserrat Bold'), ('POPPINS_BOLD', 'Poppins Bold'), ('INTER_BOLD', 'Inter Bold'), ('ROBOTO_BOLD', 'Roboto Bold'), ('OSWALD_BOLD', 'Oswald Bold'), ('BEBAS_NEUE', 'Bebas Neue'), ('ANTON', 'Anton'), ('ARCHIVO_BLACK', 'Archivo Black'), ('BANGERS', 'Bangers'), ('PERMANENT_MARKER', 'Permanent Marker'), ('CAVEAT_BOLD', 'Caveat Bold'), ('LOBSTER', 'Lobster'), ('PLAYFAIR_DISPLAY_BOLD', 'Playfair Display Bold'), ('RIGHTEOUS', 'Righteous'), ('LUCKIEST_GUY', 'Luckiest Guy'), ('PACIFICO', 'Pacifico')], default='MONTSERRAT_BOLD', max_length=30),
        ),
        migrations.AlterField(
            model_name='clipstyleconfig',
            name='caption_style',
            field=models.CharField(choices=[('WORD_BY_WORD', 'Word by Word (karaoke)'), ('CHUNKED', 'Chunked Phrases (3-4 words)'), ('LOWER_THIRD', 'Lower Third (full segment)'), ('EMOJI_ACCENT', 'Emoji Accent (chunked + emoji)'), ('KARAOKE_HIGHLIGHT', 'Karaoke Highlight')], default='CHUNKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='clipstyleconfig',
            name='hook_font',
            field=models.CharField(choices=[('MONTSERRAT_BOLD', 'Montserrat Bold'), ('POPPINS_BOLD', 'Poppins Bold'), ('INTER_BOLD', 'Inter Bold'), ('ROBOTO_BOLD', 'Roboto Bold'), ('OSWALD_BOLD', 'Oswald Bold'), ('BEBAS_NEUE', 'Bebas Neue'), ('ANTON', 'Anton'), ('ARCHIVO_BLACK', 'Archivo Black'), ('BANGERS', 'Bangers'), ('PERMANENT_MARKER', 'Permanent Marker'), ('CAVEAT_BOLD', 'Caveat Bold'), ('LOBSTER', 'Lobster'), ('PLAYFAIR_DISPLAY_BOLD', 'Playfair Display Bold'), ('RIGHTEOUS', 'Righteous'), ('LUCKIEST_GUY', 'Luckiest Guy'), ('PACIFICO', 'Pacifico')], default='MONTSERRAT_BOLD', max_length=30),
        ),
        migrations.AlterField(
            model_name='clipstyleconfig',
            name='intro_transition',
            field=models.CharField(choices=[('NONE', 'None (hard cut)'), ('CROSSFADE', 'Crossfade'), ('FADE_BLACK', 'Fade to Black'), ('FADE_WHITE', 'Fade to White'), ('SLIDE_LEFT', 'Slide Left'), ('SLIDE_RIGHT', 'Slide Right'), ('SLIDE_UP', 'Slide Up'), ('SLIDE_DOWN', 'Slide Down'), ('WIPE_LEFT', 'Wipe Left'), ('WIPE_RIGHT', 'Wipe Right'), ('ZOOM_IN', 'Zoom In'), ('CUSTOM_ASSET', 'Custom Transition Video')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='clipstyleconfig',
            name='outro_transition',
            field=models.CharField(choices=[('NONE', 'None (hard cut)'), ('CROSSFADE', 'Crossfade'), ('FADE_BLACK', 'Fade to Black'), ('FADE_WHITE', 'Fade to White'), ('SLIDE_LEFT', 'Slide Left'), ('SLIDE_RIGHT', 'Slide Right'), ('SLIDE_UP', 'Slide Up'), ('SLIDE_DOWN', 'Slide Down'), ('WIPE_LEFT', 'Wipe Left'), ('WIPE_RIGHT', 'Wipe Right'), ('ZOOM_IN', 'Zoom In'), ('CUSTOM_ASSET', 'Custom Transition Video')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='clipstyleconfig',
            name='watermark_position',
            field=models.CharField(choices=[('TOP_LEFT', 'Top Left'), ('TOP_RIGHT', 'Top Right'), ('BOTTOM_LEFT', 'Bottom Left'), ('BOTTOM_RIGHT', 'Bottom Right'), ('CENTER', 'Center'), ('TILED', 'Tiled')], default='BOTTOM_RIGHT', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliptimedoverlay',
            name='overlay_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='cliplayoutconfig',
            constraint=models.CheckConstraint(condition=models.Q(('fit_mode__in', ['CROP', 'BLUR_FILL'])), name='clips_cliplayoutconfig_fit_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('caption_style__in', ['WORD_BY_WORD', 'CHUNKED', 'LOWER_THIRD', 'EMOJI_ACCENT', 'KARAOKE_HIGHLIGHT'])), name='clips_clipstyleconfig_caption_style_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('intro_transition__in', ['NONE', 'CROSSFADE', 'FADE_BLACK', 'FADE_WHITE', 'SLIDE_LEFT', 'SLIDE_RIGHT', 'SLIDE_UP', 'SLIDE_DOWN', 'WIPE_LEFT', 'WIPE_RIGHT', 'ZOOM_IN', 'CUSTOM_ASSET'])), name='clips_clipstyleconfig_intro_transition_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('outro_transition__in', ['NONE', 'CROSSFADE', 'FADE_BLACK', 'FADE_WHITE', 'SLIDE_LEFT', 'SLIDE_RIGHT', 'SLIDE_UP', 'SLIDE_DOWN', 'WIPE_LEFT', 'WIPE_RIGHT', 'ZOOM_IN', 'CUSTOM_ASSET'])), name='clips_clipstyleconfig_outro_transition_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('watermark_position__in', ['TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT', 'CENTER', 'TILED'])), name='clips_clipstyleconfig_watermark_position_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('hook_animation__in', ['NONE', 'FADE', 'POP', 'SLIDE_LEFT', 'SLIDE_RIGHT', 'SLIDE_UP', 'SLIDE_DOWN'])), name='clips_clipstyleconfig_hook_animation_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('color_filter__in', ['NONE', 'VIVID', 'MOODY', 'WARM', 'COOL', 'BLACK_WHITE', 'VINTAGE'])), name='clips_clipstyleconfig_color_filter_valid'),
        ),
        migrations.AddConstraint(
            model_name='cliptimedoverlay',
            constraint=models.CheckConstraint(condition=models.Q(('overlay_type__in', ['TEXT', 'IMAGE', 'VIDEO'])), name='clips_cliptimedoverlay_overlay_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='cliptimedoverlay',
            constraint=models.CheckConstraint(condition=models.Q(('shape__in', ['RECTANGLE', 'CIRCLE', 'ROUNDED'])), name='clips_cliptimedoverlay_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='cliptimedoverlay',
            constraint=models.CheckConstraint(condition=models.Q(('animation__in', ['NONE', 'FADE', 'POP', 'SLIDE_LEFT', 'SLIDE_RIGHT', 'SLIDE_UP', 'SLIDE_DOWN'])), name='clips_cliptimedoverlay_animation_valid'),
        ),
        migrations.AddField(
            model_name='cliptimedsfx',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_sfx', to='clips.clipcandidate'),
        ),
        migrations.AddField(
            model_name='cliptimedsfx',
            name='sfx_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.libraryasset'),
        ),
    ]
