# Generated by Django 6.0.6 on 2026-07-06 15:47

from django.db import migrations, models


def migrate_legacy_font_values(apps, schema_editor) -> None:
    """Map legacy Montserrat-Bold strings to CaptionFont enum values."""
    ClipStyleConfig = apps.get_model('clips', 'ClipStyleConfig')
    ClipStyleConfig.objects.filter(caption_font='Montserrat-Bold').update(
        caption_font='MONTSERRAT_BOLD',
    )
    ClipStyleConfig.objects.filter(hook_font='Montserrat-Bold').update(
        hook_font='MONTSERRAT_BOLD',
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('assets', '0004_libraryasset_mime'),
        ('clips', '0006_cliptimedsfx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_font_values,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('caption_font__in', ['MONTSERRAT_BOLD', 'POPPINS_BOLD', 'INTER_BOLD', 'ROBOTO_BOLD', 'OSWALD_BOLD', 'BEBAS_NEUE', 'ANTON', 'ARCHIVO_BLACK', 'BANGERS', 'PERMANENT_MARKER', 'CAVEAT_BOLD', 'LOBSTER', 'PLAYFAIR_DISPLAY_BOLD', 'RIGHTEOUS', 'LUCKIEST_GUY', 'PACIFICO'])), name='clips_clipstyleconfig_caption_font_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('hook_font__in', ['MONTSERRAT_BOLD', 'POPPINS_BOLD', 'INTER_BOLD', 'ROBOTO_BOLD', 'OSWALD_BOLD', 'BEBAS_NEUE', 'ANTON', 'ARCHIVO_BLACK', 'BANGERS', 'PERMANENT_MARKER', 'CAVEAT_BOLD', 'LOBSTER', 'PLAYFAIR_DISPLAY_BOLD', 'RIGHTEOUS', 'LUCKIEST_GUY', 'PACIFICO'])), name='clips_clipstyleconfig_hook_font_valid'),
        ),
        migrations.AddConstraint(
            model_name='clipstyleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('watermark_font__in', ['MONTSERRAT_BOLD', 'POPPINS_BOLD', 'INTER_BOLD', 'ROBOTO_BOLD', 'OSWALD_BOLD', 'BEBAS_NEUE', 'ANTON', 'ARCHIVO_BLACK', 'BANGERS', 'PERMANENT_MARKER', 'CAVEAT_BOLD', 'LOBSTER', 'PLAYFAIR_DISPLAY_BOLD', 'RIGHTEOUS', 'LUCKIEST_GUY', 'PACIFICO'])), name='clips_clipstyleconfig_watermark_font_valid'),
        ),
        migrations.AddConstraint(
            model_name='cliptimedoverlay',
            constraint=models.CheckConstraint(condition=models.Q(('font__in', ['MONTSERRAT_BOLD', 'POPPINS_BOLD', 'INTER_BOLD', 'ROBOTO_BOLD', 'OSWALD_BOLD', 'BEBAS_NEUE', 'ANTON', 'ARCHIVO_BLACK', 'BANGERS', 'PERMANENT_MARKER', 'CAVEAT_BOLD', 'LOBSTER', 'PLAYFAIR_DISPLAY_BOLD', 'RIGHTEOUS', 'LUCKIEST_GUY', 'PACIFICO'])), name='clips_cliptimedoverlay_font_valid'),
        ),
    ]
