# Generated by Django 6.0.6 on 2026-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_clipstyleconfig_clips_clipstyleconfig_caption_font_valid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipcandidate',
            options={'ordering': ['-virality_score', '-relevance_score']},
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='flow_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='flow_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='hook_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='hook_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='intent_match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='score_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='trend_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='value_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='value_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipcandidate',
            name='virality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clipsource',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clipsource',
            name='pending_run_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
