# Generated by Django 6.0.6 on 2026-07-19 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_backfill_license_type'),
        ('channels', '0006_assemblystyleconfig'),
        ('clips', '0008_clip_virality_and_run_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipBrandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('archived', models.BooleanField(default=False)),
                ('render_format', models.CharField(choices=[('VERTICAL_9_16', 'Vertical 9:16'), ('LANDSCAPE_16_9', 'Landscape 16:9'), ('SQUARE_1_1', 'Square 1:1')], default='VERTICAL_9_16', max_length=20)),
                ('render_mode', models.CharField(choices=[('SMART_CROP', 'Smart Crop (speaker-aware)'), ('SPATIAL_STACK', 'Spatial Stack (two regions)'), ('CENTER_CROP', 'Center Crop (static)')], default='SMART_CROP', max_length=20)),
                ('fit_mode', models.CharField(choices=[('CROP', 'Crop'), ('BLUR_FILL', 'Blurred Background Fill')], default='CROP', max_length=10)),
                ('caption_preset_key', models.CharField(blank=True, default='', max_length=40)),
                ('logo_position', models.CharField(choices=[('TOP_LEFT', 'Top Left'), ('TOP_RIGHT', 'Top Right'), ('BOTTOM_LEFT', 'Bottom Left'), ('BOTTOM_RIGHT', 'Bottom Right'), ('CENTER', 'Center'), ('TILED', 'Tiled')], default='BOTTOM_RIGHT', max_length=15)),
                ('logo_opacity', models.FloatField(default=0.85)),
                ('music_volume_db', models.FloatField(default=-20.0)),
                ('keyword_highlighter', models.BooleanField(default=True)),
                ('auto_transitions', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_brand_templates', to='channels.channel')),
                ('intro_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset')),
                ('logo_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset')),
                ('music_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset')),
                ('outro_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.libraryasset')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('render_format__in', ['VERTICAL_9_16', 'LANDSCAPE_16_9', 'SQUARE_1_1'])), name='clips_clipbrandtemplate_render_format_valid'), models.CheckConstraint(condition=models.Q(('render_mode__in', ['SMART_CROP', 'SPATIAL_STACK', 'CENTER_CROP'])), name='clips_clipbrandtemplate_render_mode_valid'), models.CheckConstraint(condition=models.Q(('fit_mode__in', ['CROP', 'BLUR_FILL'])), name='clips_clipbrandtemplate_fit_mode_valid'), models.CheckConstraint(condition=models.Q(('logo_position__in', ['TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT', 'CENTER', 'TILED'])), name='clips_clipbrandtemplate_logo_position_valid')],
            },
        ),
    ]
