# Generated by Django 6.0.6 on 2026-07-19 19:14

from django.db import migrations, models


def _map_blur_fill_rows(apps, schema_editor):  # noqa: ANN001
    """Map legacy BLUR_FILL rows onto CONTAIN + BLURRED_SOURCE."""
    for model_name in ('ClipLayoutConfig', 'ClipBrandTemplate'):
        model = apps.get_model('clips', model_name)
        model.objects.filter(fit_mode='BLUR_FILL').update(
            foreground_treatment='CONTAIN',
            background_mode='BLURRED_SOURCE',
        )


def _noop_reverse(apps, schema_editor):  # noqa: ANN001
    return


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0006_backfill_license_type'),
        ('channels', '0006_assemblystyleconfig'),
        ('clips', '0009_clip_brand_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipbrandtemplate',
            name='background_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='clipbrandtemplate',
            name='background_mode',
            field=models.CharField(
                choices=[
                    ('SOLID', 'Solid color'),
                    ('BLURRED_SOURCE', 'Blurred source video'),
                ],
                default='SOLID',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='clipbrandtemplate',
            name='blur_strength',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='clipbrandtemplate',
            name='foreground_treatment',
            field=models.CharField(
                choices=[
                    ('FILL', 'Fill (crop to canvas)'),
                    ('CONTAIN', 'Contain (preserve aspect in middle zone)'),
                    ('SQUARE_CROP', 'Square crop (1:1 in middle zone)'),
                ],
                default='FILL',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='cliplayoutconfig',
            name='background_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='cliplayoutconfig',
            name='background_mode',
            field=models.CharField(
                choices=[
                    ('SOLID', 'Solid color'),
                    ('BLURRED_SOURCE', 'Blurred source video'),
                ],
                default='SOLID',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='cliplayoutconfig',
            name='blur_strength',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='cliplayoutconfig',
            name='foreground_treatment',
            field=models.CharField(
                choices=[
                    ('FILL', 'Fill (crop to canvas)'),
                    ('CONTAIN', 'Contain (preserve aspect in middle zone)'),
                    ('SQUARE_CROP', 'Square crop (1:1 in middle zone)'),
                ],
                default='FILL',
                max_length=20,
            ),
        ),
        migrations.RunPython(_map_blur_fill_rows, _noop_reverse),
        migrations.AddConstraint(
            model_name='clipbrandtemplate',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'foreground_treatment__in',
                    ['FILL', 'CONTAIN', 'SQUARE_CROP'],
                )),
                name='clips_clipbrandtemplate_foreground_treatment_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='clipbrandtemplate',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'background_mode__in',
                    ['SOLID', 'BLURRED_SOURCE'],
                )),
                name='clips_clipbrandtemplate_background_mode_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cliplayoutconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'foreground_treatment__in',
                    ['FILL', 'CONTAIN', 'SQUARE_CROP'],
                )),
                name='clips_cliplayoutconfig_foreground_treatment_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='cliplayoutconfig',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'background_mode__in',
                    ['SOLID', 'BLURRED_SOURCE'],
                )),
                name='clips_cliplayoutconfig_background_mode_valid',
            ),
        ),
    ]
