# Generated by Django 6.0.6 on 2026-08-21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelResearchJob',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'source_channel_url',
                    models.CharField(max_length=500),
                ),
                (
                    'target_market',
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    'working_name',
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('LONGFORM', 'Long-form'),
                            ('SHORTS', 'Shorts'),
                            ('CLIPPING', 'Clipping'),
                        ],
                        default='LONGFORM',
                        max_length=10,
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                (
                    'source_channel_id',
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    'source_channel_name',
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('QUEUED', 'Queued'),
                            ('RUNNING', 'Running'),
                            ('SUCCEEDED', 'Succeeded'),
                            ('FAILED', 'Failed'),
                        ],
                        default='PENDING',
                        max_length=12,
                    ),
                ),
                (
                    'research_report',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'channel_spec',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'tool_trace',
                    models.JSONField(blank=True, default=list),
                ),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='channel_research_jobs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'status__in',
                                [
                                    'PENDING',
                                    'QUEUED',
                                    'RUNNING',
                                    'SUCCEEDED',
                                    'FAILED',
                                ],
                            ),
                        ),
                        name='channel_research_job_status_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'kind__in',
                                ['LONGFORM', 'SHORTS', 'CLIPPING'],
                            ),
                        ),
                        name='channel_research_job_kind_valid',
                    ),
                ],
            },
        ),
    ]
