# Generated by Django 6.0.6 on 2026-09-02 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('channel_research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channelresearchjob',
            name='deep_analysis_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='channelresearchjob',
            name='deep_analysis_job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='channelresearchjob',
            name='deep_analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelresearchjob',
            name='deep_analysis_status',
            field=models.CharField(
                choices=[
                    ('NOT_STARTED', 'Not started'),
                    ('RUNNING', 'Running'),
                    ('SUCCEEDED', 'Succeeded'),
                    ('FAILED', 'Failed'),
                ],
                default='NOT_STARTED',
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name='channelresearchjob',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'deep_analysis_status__in',
                    ['NOT_STARTED', 'RUNNING', 'SUCCEEDED', 'FAILED'],
                )),
                name='channel_research_job_deep_analysis_status_valid',
            ),
        ),
    ]
