# Generated by Django 6.0.6 on 2026-06-19 04:09

from django.db import migrations

_CLIPPING_V1_GRAPH = {
    'stages': [
        {'key': 'clip_ingest', 'depends_on': []},
        {'key': 'clip_transcribe', 'depends_on': ['clip_ingest']},
        {
            'key': 'clip_analyze',
            'depends_on': ['clip_transcribe'],
            'config': {'clips_requested': 5},
        },
        {'key': 'clip_approval_gate', 'depends_on': ['clip_analyze'], 'gate': True},
        {'key': 'clip_render', 'depends_on': ['clip_approval_gate']},
        {'key': 'clip_distribute', 'depends_on': ['clip_render']},
    ],
}


def _add_blueprint(apps, schema_editor):
    PipelineBlueprint = apps.get_model('pipelines', 'PipelineBlueprint')
    PipelineBlueprint.objects.get_or_create(
        name='clipping_v1',
        defaults={
            'kind': 'CLIPPING',
            'graph': _CLIPPING_V1_GRAPH,
            'is_active': True,
            'version': 1,
        },
    )


def _remove_blueprint(apps, schema_editor):
    PipelineBlueprint = apps.get_model('pipelines', 'PipelineBlueprint')
    PipelineBlueprint.objects.filter(name='clipping_v1').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_pipelineblueprint_pipelines_pipelineblueprint_kind_valid_and_more'),
    ]

    operations = [
        migrations.RunPython(_add_blueprint, _remove_blueprint),
    ]
