# Generated by Django 6.0.6 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_add_clipping_v1_blueprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
