# Generated by Django 6.0.6 on 2026-06-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_phase7'),
        ('pipelines', '0004_pipelinerun_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='source_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_runs', to='ideas.topicidea'),
        ),
    ]
