# Generated by Django 6.0.6 on 2026-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channel_max_publishes_per_day'),
        ('ideas', '0001_phase7'),
        ('pipelines', '0006_add_clipping_v1_manual_blueprint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pipelinerun',
            name='pipelines_pipelinerun_status_valid',
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('AWAITING_REVIEW', 'Awaiting review'), ('BUDGET_HOLD', 'Budget hold'), ('PUBLISH_HOLD', 'Publish hold'), ('PUBLISHING', 'Publishing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pipelinerun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'AWAITING_REVIEW', 'BUDGET_HOLD', 'PUBLISH_HOLD', 'PUBLISHING', 'COMPLETED', 'FAILED', 'CANCELLED'])), name='pipelines_pipelinerun_status_valid'),
        ),
    ]
