# Generated by Django 6.0.6 on 2026-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_remove_pipelinerun_pipelines_pipelinerun_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='script_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
