# Generated by Django 6.0.6 on 2026-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_pipelinerun_script_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='had_manual_edits',
            field=models.BooleanField(default=False),
        ),
    ]
