# Generated by Django 6.0.6 on 2026-07-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_runcast_importance_draft_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runcast',
            name='design_status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('DEMOTED', 'Demoted'), ('TEXT_ONLY', 'Text only')], default='PROPOSED', max_length=10),
        ),
    ]
