# Generated by Django 6.0.6 on 2026-06-13 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fiction', models.BooleanField(default=False)),
                ('narration_pov', models.CharField(default='narrator', max_length=30)),
                ('beats', models.JSONField()),
                ('pacing', models.JSONField(default=dict)),
                ('prompt_overrides', models.JSONField(default=dict)),
                ('music_mood_map', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=60, unique=True)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('NICHE', 'Niche'), ('CHANNEL', 'Channel')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('scope__in', ['GLOBAL', 'NICHE', 'CHANNEL'])), name='prompts_prompttemplate_scope_valid')],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('model', models.CharField(default='claude-opus-4-8', max_length=60)),
                ('temperature', models.FloatField(default=1.0)),
                ('max_tokens', models.PositiveIntegerField(default=8192)),
                ('is_active', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompttemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='uq_prompt_template_version')],
            },
        ),
    ]
