# Generated by Django 6.0.6 on 2026-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_default_blueprint_name'),
        ('prompts', '0002_alter_promptversion_model_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyformat',
            name='niches',
            field=models.ManyToManyField(blank=True, related_name='format_pool', to='channels.nicheconfig'),
        ),
    ]
