#!/bin/bash

set -o errexit
set -o nounset

exec python -m debugpy --listen 0.0.0.0:5679 \
    -m celery \
    -A config.celery_app worker \
    -l INFO \
    --pool=solo \
    -Q default,orchestration,research,clipping,rendering,uploads,analytics
