#!/bin/bash

set -o errexit
set -o nounset

exec python -c "
import pydevd_pycharm
pydevd_pycharm.settrace('host.docker.internal', port=5679, stdout_to_server=True, stderr_to_server=True, suspend=False)
import sys
sys.argv = ['celery', '-A', 'config.celery_app', 'worker', '-l', 'INFO', '-Q', 'default,orchestration,research,rendering,uploads,analytics']
import runpy
runpy.run_module('celery', run_name='__main__')
"
