# Generated by Django 6.0.6 on 2026-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRoi',
            fields=[
                ('channel_id', models.UUIDField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=120)),
                ('run_count', models.IntegerField()),
                ('completed_count', models.IntegerField()),
                ('total_spend_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('avg_cost_usd', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'analytics_channel_roi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunCostSummary',
            fields=[
                ('run_id', models.UUIDField(primary_key=True, serialize=False)),
                ('channel_id', models.UUIDField()),
                ('status', models.CharField(max_length=20)),
                ('topic', models.TextField()),
                ('total_cost_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('duration_s', models.FloatField(null=True)),
                ('cost_by_provider', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'analytics_run_cost_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagePerformance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage_key', models.CharField(max_length=64)),
                ('channel_id', models.UUIDField()),
                ('execution_count', models.IntegerField()),
                ('avg_duration_s', models.FloatField(null=True)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('avg_cost_per_execution_usd', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'analytics_stage_performance',
                'managed': False,
            },
        ),
    ]
