# Generated by Django 6.0.6 on 2026-07-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishJobMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('avg_view_duration_s', models.FloatField(default=0.0)),
                ('avg_view_percentage', models.FloatField(default=0.0)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('impressions_ctr', models.FloatField(blank=True, null=True)),
                ('retention_curve', models.JSONField(default=list)),
                ('publish_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publishing.publishjob')),
            ],
            options={
                'db_table': 'analytics_publish_job_metric',
                'ordering': ['-pulled_at'],
            },
        ),
    ]
