"""Quota costs and per-section staleness windows for NexLev data."""

from datetime import timedelta

ABOUT_STALE_AFTER = timedelta(days=14)
OUTLIERS_STALE_AFTER = timedelta(days=7)
ANALYTICS_STALE_AFTER = timedelta(days=30)
SIMILAR_CHANNELS_STALE_AFTER = timedelta(days=45)
NICHE_OVERVIEW_STALE_AFTER = timedelta(days=45)
VIDEO_STALE_AFTER = timedelta(days=90)
SEARCH_CACHE_TTL = timedelta(hours=24)

QUOTA_COST_ABOUT = 1
QUOTA_COST_OUTLIERS = 1
QUOTA_COST_ANALYTICS = 10
QUOTA_COST_SIMILAR_CHANNELS = 20
QUOTA_COST_NICHE_OVERVIEW = 20
QUOTA_COST_CHANNEL_ANALYSIS_CREATE = 20
QUOTA_COST_CHANNEL_ANALYSIS_STATUS = 1
QUOTA_COST_VIDEO_DETAILS = 1
QUOTA_COST_VIDEO_TRANSCRIPT = 1
QUOTA_COST_VIDEO_COMMENTS = 1
QUOTA_COST_SEARCH = 1
