# Generated by Django 6.0.6 on 2026-06-19 06:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_character_source_run'),
        ('pipelines', '0004_pipelinerun_is_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROMOTED', 'Promoted')], default='BACKLOG', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_ideas', to='channels.channel')),
                ('niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_ideas', to='channels.nicheconfig')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ideas', to='pipelines.pipelinerun')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['BACKLOG', 'APPROVED', 'REJECTED', 'PROMOTED'])), name='ideas_topicidea_status_valid')],
            },
        ),
    ]
