# Generated by Django 6.0.6 on 2026-07-07 17:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channel_max_publishes_per_day'),
        ('ideas', '0001_phase7'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicheOutlierScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=200)),
                ('results', models.JSONField(default=list)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlier_scans', to='channels.nicheconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
